// DigiYar V5.1 Data Ingestion Engine
export const MAX_PRODUCTS_PER_CATEGORY=500;
export const SOURCE_TTL_MS=6*60*60*1000;
export function normalizeText(s=''){return String(s).toLowerCase().replace(/[يى]/g,'ی').replace(/ك/g,'ک').replace(/\s+/g,' ').trim()}
export function normalizeObservation(o={}){return{productId:String(o.productId||o.id||o.sku||''),name:o.name||o.productName||'',brand:o.brand||'',model:o.model||'',category:o.category||'',storeId:o.storeId||o.store||'',storeName:o.storeName||o.store||'',price:Number(o.price||0),currency:o.currency||'IRR',available:o.available===true||o.availability==='in_stock',availability:o.availability||(o.available===false?'out_of_stock':'unknown'),productUrl:o.productUrl||o.url||'',affiliateUrl:o.affiliateUrl||'',source:o.source||'',observedAt:o.observedAt||new Date().toISOString()}}
export function isFresh(o,now=Date.now(),ttl=SOURCE_TTL_MS){const t=Date.parse(o.observedAt||'');return Number.isFinite(t)&&(now-t)<=ttl}
export function upsertProduct(catalog,observation){const o=normalizeObservation(observation);if(!o.productId)return catalog;const idx=catalog.findIndex(p=>String(p.id)===o.productId);if(idx<0){if(catalog.length>=MAX_PRODUCTS_PER_CATEGORY)return catalog;catalog.push({id:o.productId,name:o.name,brand:o.brand,model:o.model,category:o.category,offers:[o]});return catalog}const p=catalog[idx];p.name=p.name||o.name;p.brand=p.brand||o.brand;p.model=p.model||o.model;p.category=p.category||o.category;const oi=p.offers.findIndex(x=>String(x.storeId)===String(o.storeId));if(oi<0)p.offers.push(o);else p.offers[oi]={...p.offers[oi],...o};return catalog}
export function reconcile(catalog,observations,now=Date.now()){for(const raw of observations){const o=normalizeObservation(raw);if(!isFresh(o,now))continue;upsertProduct(catalog,o)}return catalog}
export function availabilitySnapshot(product,now=Date.now()){const offers=(product.offers||[]).map(o=>({...o,stale:!isFresh(o,now)}));return{productId:product.id,offers,available:offers.some(o=>!o.stale&&o.available),bestPrice:Math.min(...offers.filter(o=>!o.stale&&o.available&&o.price>0).map(o=>o.price),Infinity)}}
export function trimCategory(catalog){return catalog.slice(0,MAX_PRODUCTS_PER_CATEGORY)}
const AFF={digikala:'https://aflo.ir/TrvNHEN8',snappshop:'https://aflo.ir/YPN05dL7'};
const productUrlOk=u=>{try{const x=new URL(u);return /^https?:$/.test(x.protocol)&&!/\/search(?:\/|\?|$)/i.test(x.pathname)&&!/(google|bing|duckduckgo|jina\.ai)/i.test(x.hostname)}catch{return false}};
const aff=(store,url)=>AFF[store]&&productUrlOk(url)?`${AFF[store]}?p=${encodeURIComponent(url)}`:'';
async function fetchRaw(url,headers={}){const r=await fetch(url,{redirect:'manual',headers});if(r.status>=300&&r.status<400)throw Error(`REDIRECT ${r.status} ${r.headers.get('location')||url}`);if(!r.ok)throw Error(`HTTP ${r.status}`);return r}
async function getJson(url){return(await fetchRaw(url,{Accept:'application/json','User-Agent':'DigiYar/5.1'})).json()}
async function getHtml(url){return(await fetchRaw(url,{Accept:'text/html,application/xhtml+xml','Accept-Language':'fa-IR,fa;q=0.9,en;q=0.8','User-Agent':'Mozilla/5.0 (compatible; DigiYar/5.1)'})).text()}
async function getReader(url){return(await fetchRaw(`https://r.jina.ai/${url}`,{Accept:'text/plain','User-Agent':'DigiYar/5.1'})).text()}
function collect(x,out){if(!x)return;if(Array.isArray(x)){x.forEach(v=>collect(v,out));return}if(typeof x!=='object')return;const t=String(x['@type']||'').toLowerCase();if(t.includes('product')&&(x.url||x.sku||x.productID)){const o=Array.isArray(x.offers)?x.offers[0]:x.offers||{};out.push({productId:String(x.sku||x.productID||x.mpn||''),name:x.name||'',price:Number(o.price||0)||0,currency:o.priceCurrency||'IRR',availability:o.availability||'unknown',productUrl:x.url||''})}Object.values(x).forEach(v=>v&&typeof v==='object'&&collect(v,out))}
function extractJsonLd(html){const out=[],re=/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;let m;while((m=re.exec(html))){try{collect(JSON.parse(m[1]),out)}catch{}}return out}
function cleanUrl(u){try{return decodeURIComponent(u).replace(/&amp;/g,'&').replace(/[.,;]+$/,'')}catch{return u.replace(/&amp;/g,'&').replace(/[.,;]+$/,'')}}
function extractLinks(text,domain){const out=[];const add=u=>{const x=cleanUrl(u);if(x.includes(domain)&&!x.includes('/search')&&!x.includes('/category')&&!x.includes('google.com')&&!x.includes('bing.com')&&!x.includes('duckduckgo.com')&&!x.includes('r.jina.ai')&&!out.includes(x))out.push(x)};let m;const md=/\]\((https?:\/\/[^)]+)\)/gi;while((m=md.exec(text))&&out.length<20)add(m[1]);const abs=/https?:\/\/[^\s\)\]"'<>]+/gi;while((m=abs.exec(text))&&out.length<20)add(m[0]);return out}
async function searchWeb(domain,query){const q=`site:${domain} ${query}`;const endpoints=[`https://www.bing.com/search?q=${encodeURIComponent(q)}&count=10`,`https://html.duckduckgo.com/html/?q=${encodeURIComponent(q)}`,`https://www.google.com/search?q=${encodeURIComponent(q)}&num=10`];let errors=[];for(const endpoint of endpoints){try{const h=await getReader(endpoint);const links=extractLinks(h,domain);if(links.length)return links;errors.push(`NO_LINKS:${new URL(endpoint).hostname}`)}catch(e){errors.push(String(e))}}throw Error(`WEB_SEARCH_FAILED ${errors.join(' | ')}`)}
function inferFromReader(text,url,store){const id=(url.match(/(?:dkp-|product\/|p\/|item\/|sku[=/-])([0-9]+)/i)||[])[1]||'';let title='';const tm=text.match(/^#\s+(.+)$/m);if(tm)title=tm[1].trim();if(!title){const mt=text.match(/(?:title|نام محصول|product name)\s*[:：]\s*(.+)/i);if(mt)title=mt[1].trim()}const prices=[...text.matchAll(/(?:قیمت|price)[^\d]{0,30}([\d٬,\.]{4,})/gi)].map(m=>Number(m[1].replace(/[٬,]/g,'').replace(/\.0+$/,''))).filter(n=>n>1000);const price=prices[0]||0;const availability=/ناموجود|out of stock|unavailable/i.test(text)?'out_of_stock':'unknown';if(!id||!title)return null;return normalizeObservation({productId:id,name:title,price,currency:'IRR',availability,productUrl:url,affiliateUrl:aff(store,url),storeId:store,storeName:store==='digikala'?'دیجی‌کالا':'اسنپ‌شاپ',source:`${store}-reader-fallback`})}
async function enrichPages(urls,store){const out=[];for(const url of urls.slice(0,8)){try{let html;try{html=await getHtml(url)}catch{html=await getReader(url)}const ld=extractJsonLd(html);if(ld.length){for(const x of ld){if(!x.productId&&productUrlOk(url))x.productId=(url.match(/(?:dkp-|product\/|p\/|item\/)([0-9]+)/i)||[])[1]||'';if(!x.productUrl)x.productUrl=url;if(x.productId&&x.name)out.push(normalizeObservation({...x,productUrl:url,affiliateUrl:aff(store,url),storeId:store,storeName:store==='digikala'?'دیجی‌کالا':'اسنپ‌شاپ',source:`${store}-web-fallback`}))}}else{const x=inferFromReader(html,url,store);if(x)out.push(x)}}catch{}}return out.filter(x=>x.productId&&productUrlOk(x.productUrl))}
async function fallback(store,query,originalError){try{const urls=await searchWeb(store==='digikala'?'digikala.com/product':'snappshop.ir',query);const items=await enrichPages(urls,store);return{status:items.length?'fulfilled':'fulfilled_empty',items,rawCount:items.length,method:'web_fallback',error:items.length?'':String(originalError),searchedUrls:urls.length}}catch(e){return{status:'rejected',items:[],rawCount:0,method:'web_fallback',error:`${String(originalError)} | ${String(e)}`,searchedUrls:0}}}
export async function ingestDigikala(query){try{const d=await getJson(`https://api.digikala.com/v1/search/?q=${encodeURIComponent(query)}&page=1`);const raw=d?.data?.products||d?.data?.data?.products||[];const items=raw.slice(0,MAX_PRODUCTS_PER_CATEGORY).map(x=>{const id=x?.id||x?.product_id||x?.product?.id,url=id?`https://www.digikala.com/product/dkp-${id}/`:'';const v=x?.default_variant||x?.variants?.[0]||{};return normalizeObservation({productId:id,name:x?.title_fa||x?.title_en||'',brand:x?.brand?.title_fa||x?.brand?.title||'',price:v?.price?.selling_price??x?.price?.selling_price??0,currency:'IRR',availability:id?'in_stock':'unknown',productUrl:url,affiliateUrl:aff('digikala',url),storeId:'digikala',storeName:'دیجی‌کالا',source:'digikala-api'})}).filter(x=>x.productId&&productUrlOk(x.productUrl));if(items.length)return{status:'fulfilled',items,rawCount:raw.length,method:'api'};return await fallback('digikala',query,'API_EMPTY')}catch(error){return await fallback('digikala',query,String(error))}}
export async function ingestSnappshop(query){try{const html=await getHtml(`https://snappshop.ir/search?q=${encodeURIComponent(query)}`);const raw=extractJsonLd(html);const items=raw.map(x=>normalizeObservation({...x,affiliateUrl:aff('snappshop',x.productUrl),storeId:'snappshop',storeName:'اسنپ‌شاپ',source:'snappshop-jsonld'})).filter(x=>x.productId&&productUrlOk(x.productUrl)).slice(0,MAX_PRODUCTS_PER_CATEGORY);if(items.length)return{status:'fulfilled',items,rawCount:raw.length,method:'jsonld'};return await fallback('snappshop',query,'JSONLD_EMPTY')}catch(error){return await fallback('snappshop',query,String(error))}}
export async function ingestCategory(query){const [digikala,snappshop]=await Promise.all([ingestDigikala(query),ingestSnappshop(query)]);return{success:true,query,generatedAt:new Date().toISOString(),sources:{digikala,snappshop},items:[...digikala.items,...snappshop.items]}}
