// DigiYar V5.1 Data Ingestion Engine
// Independent public-source adapters + normalized Product/Offer observations.
export const MAX_PRODUCTS_PER_CATEGORY=500;
export const SOURCE_TTL_MS=6*60*60*1000;
export function normalizeText(s=''){return String(s).toLowerCase().replace(/[يى]/g,'ی').replace(/ك/g,'ک').replace(/\s+/g,' ').trim()}
export function normalizeObservation(o={}){return{productId:String(o.productId||o.id||o.sku||''),name:o.name||o.productName||'',brand:o.brand||'',model:o.model||'',category:o.category||'',storeId:o.storeId||o.store||'',storeName:o.storeName||o.store||'',price:Number(o.price||0),currency:o.currency||'IRR',available:o.available===true||o.availability==='in_stock',availability:o.availability||(o.available===false?'out_of_stock':'unknown'),productUrl:o.productUrl||o.url||'',affiliateUrl:o.affiliateUrl||'',source:o.source||'',observedAt:o.observedAt||new Date().toISOString()}}
export function isFresh(o,now=Date.now(),ttl=SOURCE_TTL_MS){const t=Date.parse(o.observedAt||'');return Number.isFinite(t)&&(now-t)<=ttl}
export function upsertProduct(catalog,observation){const o=normalizeObservation(observation);if(!o.productId)return catalog;const idx=catalog.findIndex(p=>String(p.id)===o.productId);if(idx<0){if(catalog.length>=MAX_PRODUCTS_PER_CATEGORY)return catalog;catalog.push({id:o.productId,name:o.name,brand:o.brand,model:o.model,category:o.category,offers:[o]});return catalog}const p=catalog[idx];p.name=p.name||o.name;p.brand=p.brand||o.brand;p.model=p.model||o.model;p.category=p.category||o.category;const oi=p.offers.findIndex(x=>String(x.storeId)===String(o.storeId));if(oi<0)p.offers.push(o);else p.offers[oi]={...p.offers[oi],...o};return catalog}
export function reconcile(catalog,observations,now=Date.now()){for(const raw of observations){const o=normalizeObservation(raw);if(!isFresh(o,now))continue;upsertProduct(catalog,o)}return catalog}
export function availabilitySnapshot(product,now=Date.now()){const offers=(product.offers||[]).map(o=>({...o,stale:!isFresh(o,now)}));return{productId:product.id,offers,available:offers.some(o=>!o.stale&&o.available),bestPrice:Math.min(...offers.filter(o=>!o.stale&&o.available&&o.price>0).map(o=>o.price),Infinity)}}
export function trimCategory(catalog){return catalog.slice(0,MAX_PRODUCTS_PER_CATEGORY)}

const AFF={digikala:'https://aflo.ir/TrvNHEN8',snappshop:'https://aflo.ir/YPN05dL7'};
const productUrlOk=u=>{try{const x=new URL(u);return /^https?:$/.test(x.protocol)&&!/\/search(?:\/|\?|$)/i.test(x.pathname)}catch{return false}};
const aff=(store,url)=>AFF[store]&&productUrlOk(url)?`${AFF[store]}?p=${encodeURIComponent(url)}`:'';
async function getJson(url){const r=await fetch(url,{redirect:'follow',headers:{Accept:'application/json','User-Agent':'DigiYar/5.1'}});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}
async function getHtml(url){const r=await fetch(url,{redirect:'follow',headers:{Accept:'text/html,application/xhtml+xml','Accept-Language':'fa-IR,fa;q=0.9','User-Agent':'Mozilla/5.0 (compatible; DigiYar/5.1)'}});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.text()}
export async function ingestDigikala(query){try{const d=await getJson(`https://api.digikala.com/v1/search/?q=${encodeURIComponent(query)}&page=1`);const raw=d?.data?.products||d?.data?.data?.products||[];const items=raw.slice(0,MAX_PRODUCTS_PER_CATEGORY).map(x=>{const id=x?.id||x?.product_id||x?.product?.id,url=id?`https://www.digikala.com/product/dkp-${id}/`:'';const v=x?.default_variant||x?.variants?.[0]||{};const price=v?.price?.selling_price??x?.price?.selling_price??0;return normalizeObservation({productId:id,name:x?.title_fa||x?.title_en||'',brand:x?.brand?.title_fa||x?.brand?.title||'',price,currency:'IRR',availability:id?'in_stock':'unknown',productUrl:url,affiliateUrl:aff('digikala',url),storeId:'digikala',storeName:'دیجی‌کالا',source:'digikala-api'})}).filter(x=>x.productId&&productUrlOk(x.productUrl));return{status:items.length?'fulfilled':'fulfilled_empty',items,rawCount:raw.length}}catch(error){return{status:'rejected',items:[],rawCount:0,error:String(error)}}}
function collect(x,out){if(!x)return;if(Array.isArray(x)){x.forEach(v=>collect(v,out));return}if(typeof x!=='object')return;const t=String(x['@type']||'').toLowerCase();if(t.includes('product')&&(x.url||x.sku||x.productID)){const o=Array.isArray(x.offers)?x.offers[0]:x.offers||{};out.push({productId:String(x.sku||x.productID||x.mpn||''),name:x.name||'',price:Number(o.price||0)||0,currency:o.priceCurrency||'IRR',availability:o.availability||'unknown',productUrl:x.url||''})}Object.values(x).forEach(v=>v&&typeof v==='object'&&collect(v,out))}
export async function ingestSnappshop(query){try{const html=await getHtml(`https://snappshop.ir/search?q=${encodeURIComponent(query)}`);const raw=[],re=/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;let m;while((m=re.exec(html))&&raw.length<MAX_PRODUCTS_PER_CATEGORY){try{collect(JSON.parse(m[1]),raw)}catch{}}const items=raw.map(x=>normalizeObservation({productId:x.productId,name:x.name,price:x.price,currency:x.currency||'IRR',availability:x.availability,productUrl:x.productUrl,affiliateUrl:aff('snappshop',x.productUrl),storeId:'snappshop',storeName:'اسنپ‌شاپ',source:'snappshop-jsonld'})).filter(x=>x.productId&&productUrlOk(x.productUrl)).slice(0,MAX_PRODUCTS_PER_CATEGORY);return{status:items.length?'fulfilled':'fulfilled_empty',items,rawCount:raw.length}}catch(error){return{status:'rejected',items:[],rawCount:0,error:String(error)}}}
export async function ingestCategory(query){const [digikala,snappshop]=await Promise.all([ingestDigikala(query),ingestSnappshop(query)]);return{success:true,query,generatedAt:new Date().toISOString(),sources:{digikala,snappshop},items:[...digikala.items,...snappshop.items]}}
