export const MOBILE_PRODUCTS = [
  {
    "id": "web-mobile-64de555dd592b28c",
    "productId": "web-mobile-64de555dd592b28c",
    "name": "Samsung Galaxy S26 Ultra",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy S26 Ultra",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-41113-samsung-galaxy-s26-ultra.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.846Z"
  },
  {
    "id": "web-mobile-13992d92c945a3cc",
    "productId": "web-mobile-13992d92c945a3cc",
    "name": "Xiaomi Redmi Note 15 Pro",
    "brand": "شیائومی",
    "model": "Xiaomi Redmi Note 15 Pro",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-41046-xiaomi-redmi-note-15-pro.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.846Z"
  },
  {
    "id": "web-mobile-780f91dd4105af59",
    "productId": "web-mobile-780f91dd4105af59",
    "name": "Xiaomi Redmi Note 15",
    "brand": "شیائومی",
    "model": "Xiaomi Redmi Note 15",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-41047-xiaomi-redmi-note-15.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.847Z"
  },
  {
    "id": "web-mobile-25b1953482f093ca",
    "productId": "web-mobile-25b1953482f093ca",
    "name": "Samsung Galaxy A36",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy A36",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40711-samsung-galaxy-a36.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.847Z"
  },
  {
    "id": "web-mobile-a489143c03de23b7",
    "productId": "web-mobile-a489143c03de23b7",
    "name": "Samsung Galaxy A56",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy A56",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40710-samsung-galaxy-a56.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.847Z"
  },
  {
    "id": "web-mobile-4f722fec7469dce7",
    "productId": "web-mobile-4f722fec7469dce7",
    "name": "Samsung Galaxy A26",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy A26",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40709-samsung-galaxy-a26.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.847Z"
  },
  {
    "id": "web-mobile-4052069ff3093f19",
    "productId": "web-mobile-4052069ff3093f19",
    "name": "Honor X5c Plus",
    "brand": "",
    "model": "Honor X5c Plus",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40968-honor-x5c-plus.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.847Z"
  },
  {
    "id": "web-mobile-84a692bdecd5d9dc",
    "productId": "web-mobile-84a692bdecd5d9dc",
    "name": "Motorola Edge 60 Fusion",
    "brand": "",
    "model": "Motorola Edge 60 Fusion",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40738-motorola-edge-60-fusion.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.847Z"
  },
  {
    "id": "web-mobile-7dd4e0dc1cb7cde3",
    "productId": "web-mobile-7dd4e0dc1cb7cde3",
    "name": "Honor 600 Lite",
    "brand": "",
    "model": "Honor 600 Lite",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-41136-honor-600-lite.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.847Z"
  },
  {
    "id": "web-mobile-7fd7cdf8b555694c",
    "productId": "web-mobile-7fd7cdf8b555694c",
    "name": "Realme C71",
    "brand": "",
    "model": "Realme C71",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40843-realme-c71.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.847Z"
  },
  {
    "id": "web-mobile-6ecf98fd018e431e",
    "productId": "web-mobile-6ecf98fd018e431e",
    "name": "Honor 600",
    "brand": "",
    "model": "Honor 600",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-41168-honor-600.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.847Z"
  },
  {
    "id": "web-mobile-bd398e36e9f5159a",
    "productId": "web-mobile-bd398e36e9f5159a",
    "name": "Honor X7e",
    "brand": "",
    "model": "Honor X7e",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-41228-honor-x7e.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.847Z"
  },
  {
    "id": "web-mobile-84057a25ee94111b",
    "productId": "web-mobile-84057a25ee94111b",
    "name": "Honor X8d",
    "brand": "",
    "model": "Honor X8d",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-41038-honor-x8d.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.847Z"
  },
  {
    "id": "web-mobile-3ccae5a4e3222368",
    "productId": "web-mobile-3ccae5a4e3222368",
    "name": "Samsung Galaxy S25 FE",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy S25 FE",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40925-samsung-galaxy-s25-fe.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.847Z"
  },
  {
    "id": "web-mobile-f6f50135d4f3e8e3",
    "productId": "web-mobile-f6f50135d4f3e8e3",
    "name": "Xiaomi Redmi 13x",
    "brand": "شیائومی",
    "model": "Xiaomi Redmi 13x",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40742-xiaomi-redmi-13x.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.847Z"
  },
  {
    "id": "web-mobile-e4ca5fdfb7fce775",
    "productId": "web-mobile-e4ca5fdfb7fce775",
    "name": "Xiaomi Poco X7 Pro",
    "brand": "شیائومی",
    "model": "Xiaomi Poco X7 Pro",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40672-xiaomi-poco-x7-pro.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.847Z"
  },
  {
    "id": "web-mobile-2d3e09123882061e",
    "productId": "web-mobile-2d3e09123882061e",
    "name": "Xiaomi Redmi Note 15 Pro 4G",
    "brand": "شیائومی",
    "model": "Xiaomi Redmi Note 15 Pro 4G",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-41048-xiaomi-redmi-note-15-pro-4g.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.847Z"
  },
  {
    "id": "web-mobile-64c4a245724d320a",
    "productId": "web-mobile-64c4a245724d320a",
    "name": "Xiaomi Redmi Note 14 Pro 5G (Global)",
    "brand": "شیائومی",
    "model": "Xiaomi Redmi Note 14 Pro 5G (Global)",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40675-xiaomi-redmi-note-14-pro-5g-global.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.847Z"
  },
  {
    "id": "web-mobile-5e7f430a37ad7c71",
    "productId": "web-mobile-5e7f430a37ad7c71",
    "name": "Apple iPhone 16",
    "brand": "اپل",
    "model": "Apple iPhone 16",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40553-apple-iphone-16.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.847Z"
  },
  {
    "id": "web-mobile-408400f8843525f9",
    "productId": "web-mobile-408400f8843525f9",
    "name": "Apple iPhone 14",
    "brand": "اپل",
    "model": "Apple iPhone 14",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-39805-apple-iphone-14.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.848Z"
  },
  {
    "id": "web-mobile-9bf0f7624053e3a4",
    "productId": "web-mobile-9bf0f7624053e3a4",
    "name": "Apple iPhone 17 Pro Max",
    "brand": "اپل",
    "model": "Apple iPhone 17 Pro Max",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40934-apple-iphone-17-pro-max.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.848Z"
  },
  {
    "id": "web-mobile-0026d2c2934cfc4e",
    "productId": "web-mobile-0026d2c2934cfc4e",
    "name": "Apple iPhone 17",
    "brand": "اپل",
    "model": "Apple iPhone 17",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40933-apple-iphone-17.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.848Z"
  },
  {
    "id": "web-mobile-538057dfb89f97da",
    "productId": "web-mobile-538057dfb89f97da",
    "name": "Apple iPhone 17 Pro",
    "brand": "اپل",
    "model": "Apple iPhone 17 Pro",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40935-apple-iphone-17-pro.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.848Z"
  },
  {
    "id": "web-mobile-43ddc9f0610ea9af",
    "productId": "web-mobile-43ddc9f0610ea9af",
    "name": "Honor 400",
    "brand": "",
    "model": "Honor 400",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40805-honor-400.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.848Z"
  },
  {
    "id": "web-mobile-e27b7cc9346e2d08",
    "productId": "web-mobile-e27b7cc9346e2d08",
    "name": "Apple iPhone 16e",
    "brand": "اپل",
    "model": "Apple iPhone 16e",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40697-apple-iphone-16e.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.848Z"
  },
  {
    "id": "web-mobile-19711fa2673174ac",
    "productId": "web-mobile-19711fa2673174ac",
    "name": "Honor X6c",
    "brand": "",
    "model": "Honor X6c",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40846-honor-x6c.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.848Z"
  },
  {
    "id": "web-mobile-71fa0dd77134c4de",
    "productId": "web-mobile-71fa0dd77134c4de",
    "name": "Honor 400 Lite",
    "brand": "",
    "model": "Honor 400 Lite",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40749-honor-400-lite.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.848Z"
  },
  {
    "id": "web-mobile-ecdd00048f65eec5",
    "productId": "web-mobile-ecdd00048f65eec5",
    "name": "Honor Play10 4G",
    "brand": "",
    "model": "Honor Play10 4G",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40946-honor-play10-4g.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.848Z"
  },
  {
    "id": "web-mobile-5a533d496d705583",
    "productId": "web-mobile-5a533d496d705583",
    "name": "Honor X7d 4G",
    "brand": "",
    "model": "Honor X7d 4G",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40919-honor-x7d-4g.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.848Z"
  },
  {
    "id": "web-mobile-d2a05191d88daae0",
    "productId": "web-mobile-d2a05191d88daae0",
    "name": "Honor X9d",
    "brand": "",
    "model": "Honor X9d",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-41017-honor-x9d.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.849Z"
  },
  {
    "id": "web-mobile-a65d511c4af377fe",
    "productId": "web-mobile-a65d511c4af377fe",
    "name": "Samsung Galaxy A57",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy A57",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-41119-samsung-galaxy-a57.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.849Z"
  },
  {
    "id": "web-mobile-4a5d08eed91a6e42",
    "productId": "web-mobile-4a5d08eed91a6e42",
    "name": "Honor 600 Pro",
    "brand": "",
    "model": "Honor 600 Pro",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-41167-honor-600-pro.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.849Z"
  },
  {
    "id": "web-mobile-6d48134b1885bfc7",
    "productId": "web-mobile-6d48134b1885bfc7",
    "name": "Honor Win RT",
    "brand": "",
    "model": "Honor Win RT",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-41055-honor-win-rt.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.849Z"
  },
  {
    "id": "web-mobile-28e95a592713f822",
    "productId": "web-mobile-28e95a592713f822",
    "name": "Vivo iQOO 15",
    "brand": "",
    "model": "Vivo iQOO 15",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40992-vivo-iqoo-15.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.849Z"
  },
  {
    "id": "web-mobile-2707da138d2c79d3",
    "productId": "web-mobile-2707da138d2c79d3",
    "name": "Vivo X300 Pro",
    "brand": "",
    "model": "Vivo X300 Pro",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40975-vivo-x300-pro.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.849Z"
  },
  {
    "id": "web-mobile-87ebb1ca6378a710",
    "productId": "web-mobile-87ebb1ca6378a710",
    "name": "OnePlus Ace 6T",
    "brand": "",
    "model": "OnePlus Ace 6T",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-41033-oneplus-ace-6t.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.849Z"
  },
  {
    "id": "web-mobile-6588e1ee788cc10c",
    "productId": "web-mobile-6588e1ee788cc10c",
    "name": "Realme Note 50",
    "brand": "",
    "model": "Realme Note 50",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40339-realme-note-50.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.849Z"
  },
  {
    "id": "web-mobile-dc0c5f8a23f05fe5",
    "productId": "web-mobile-dc0c5f8a23f05fe5",
    "name": "Xiaomi 17 Pro Max",
    "brand": "شیائومی",
    "model": "Xiaomi 17 Pro Max",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40962-xiaomi-17-pro-max.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.849Z"
  },
  {
    "id": "web-mobile-7a60a1525049772a",
    "productId": "web-mobile-7a60a1525049772a",
    "name": "Xiaomi Poco X8 Pro Max",
    "brand": "شیائومی",
    "model": "Xiaomi Poco X8 Pro Max",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-41130-xiaomi-poco-x8-pro-max.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.849Z"
  },
  {
    "id": "web-mobile-71147f0397e56106",
    "productId": "web-mobile-71147f0397e56106",
    "name": "Xiaomi Redmi Note 14 Pro+",
    "brand": "شیائومی",
    "model": "Xiaomi Redmi Note 14 Pro+",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40574-xiaomi-redmi-note-14-pro.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.849Z"
  },
  {
    "id": "web-mobile-5c883b7ce8d82540",
    "productId": "web-mobile-5c883b7ce8d82540",
    "name": "Samsung Galaxy S25 Ultra",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy S25 Ultra",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40683-samsung-galaxy-s25-ultra.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.849Z"
  },
  {
    "id": "web-mobile-3d4b745e87f64f66",
    "productId": "web-mobile-3d4b745e87f64f66",
    "name": "Xiaomi Redmi K90",
    "brand": "شیائومی",
    "model": "Xiaomi Redmi K90",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-41002-xiaomi-redmi-k90.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.849Z"
  },
  {
    "id": "web-mobile-8d5a84d79a333ced",
    "productId": "web-mobile-8d5a84d79a333ced",
    "name": "Apple iPhone 13 Pro",
    "brand": "اپل",
    "model": "Apple iPhone 13 Pro",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-39403-apple-iphone-13-pro.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.849Z"
  },
  {
    "id": "web-mobile-a682f91647473ae9",
    "productId": "web-mobile-a682f91647473ae9",
    "name": "Realme Note 60x",
    "brand": "",
    "model": "Realme Note 60x",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40646-realme-note-60x.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.849Z"
  },
  {
    "id": "web-mobile-17bdc327674873a8",
    "productId": "web-mobile-17bdc327674873a8",
    "name": "Motorola Razr Fold",
    "brand": "",
    "model": "Motorola Razr Fold",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-41211-motorola-razr-fold.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.849Z"
  },
  {
    "id": "web-mobile-9c9fd9d00575924f",
    "productId": "web-mobile-9c9fd9d00575924f",
    "name": "Motorola Edge 70 Pro",
    "brand": "",
    "model": "Motorola Edge 70 Pro",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-41202-motorola-edge-70-pro.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.850Z"
  },
  {
    "id": "web-mobile-bc58dc86fa5d6933",
    "productId": "web-mobile-bc58dc86fa5d6933",
    "name": "Xiaomi Redmi Turbo 5 Max",
    "brand": "شیائومی",
    "model": "Xiaomi Redmi Turbo 5 Max",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-41091-xiaomi-redmi-turbo-5-max.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.850Z"
  },
  {
    "id": "web-mobile-d19a27c1b5f15cff",
    "productId": "web-mobile-d19a27c1b5f15cff",
    "name": "Xiaomi 17 Pro",
    "brand": "شیائومی",
    "model": "Xiaomi 17 Pro",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40963-xiaomi-17-pro.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.850Z"
  },
  {
    "id": "web-mobile-1e4e1bc3b083e716",
    "productId": "web-mobile-1e4e1bc3b083e716",
    "name": "Honor X5b Plus",
    "brand": "",
    "model": "Honor X5b Plus",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40595-honor-x5b-plus.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.850Z"
  },
  {
    "id": "web-mobile-29adbe97235c5dbe",
    "productId": "web-mobile-29adbe97235c5dbe",
    "name": "Realme Note 60",
    "brand": "",
    "model": "Realme Note 60",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40544-realme-note-60.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.850Z"
  },
  {
    "id": "web-mobile-0564ce149bb4d0d4",
    "productId": "web-mobile-0564ce149bb4d0d4",
    "name": "Samsung Galaxy A17 4G",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy A17 4G",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40951-samsung-galaxy-a17-4g.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.850Z"
  },
  {
    "id": "web-mobile-343c6e484774f027",
    "productId": "web-mobile-343c6e484774f027",
    "name": "Realme C75",
    "brand": "",
    "model": "Realme C75",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40644-realme-c75.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.850Z"
  },
  {
    "id": "web-mobile-53018be997139f5a",
    "productId": "web-mobile-53018be997139f5a",
    "name": "Samsung Galaxy Z Flip7",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy Z Flip7",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40870-samsung-galaxy-z-flip7.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.850Z"
  },
  {
    "id": "web-mobile-faa5b066ac22b612",
    "productId": "web-mobile-faa5b066ac22b612",
    "name": "Samsung Galaxy A16",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy A16",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40587-samsung-galaxy-a16.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.850Z"
  },
  {
    "id": "web-mobile-8b96e0d4409b9fa1",
    "productId": "web-mobile-8b96e0d4409b9fa1",
    "name": "Samsung Galaxy A07 4G",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy A07 4G",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40917-samsung-galaxy-a07-4g.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.850Z"
  },
  {
    "id": "web-mobile-46fa0d1f3d29d6cc",
    "productId": "web-mobile-46fa0d1f3d29d6cc",
    "name": "Xiaomi Poco C71",
    "brand": "شیائومی",
    "model": "Xiaomi Poco C71",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40751-xiaomi-poco-c71.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.851Z"
  },
  {
    "id": "web-mobile-af8dea85eb29c980",
    "productId": "web-mobile-af8dea85eb29c980",
    "name": "Xiaomi Redmi A5 4G",
    "brand": "شیائومی",
    "model": "Xiaomi Redmi A5 4G",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40743-xiaomi-redmi-a5-4g.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.851Z"
  },
  {
    "id": "web-mobile-29d3b967ae6c2438",
    "productId": "web-mobile-29d3b967ae6c2438",
    "name": "Xiaomi Redmi Note 14S",
    "brand": "شیائومی",
    "model": "Xiaomi Redmi Note 14S",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40727-xiaomi-redmi-note-14s.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.851Z"
  },
  {
    "id": "web-mobile-bffa0ca05e8fd5af",
    "productId": "web-mobile-bffa0ca05e8fd5af",
    "name": "Xiaomi Poco C85 4G",
    "brand": "شیائومی",
    "model": "Xiaomi Poco C85 4G",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40922-xiaomi-poco-c85-4g.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.851Z"
  },
  {
    "id": "web-mobile-2805ca4467e2a869",
    "productId": "web-mobile-2805ca4467e2a869",
    "name": "Xiaomi Poco M8 Pro",
    "brand": "شیائومی",
    "model": "Xiaomi Poco M8 Pro",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-41072-xiaomi-poco-m8-pro.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.851Z"
  },
  {
    "id": "web-mobile-f914b9c66b3d05c6",
    "productId": "web-mobile-f914b9c66b3d05c6",
    "name": "Samsung Galaxy A27",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy A27",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-41236-samsung-galaxy-a27.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.851Z"
  },
  {
    "id": "web-mobile-7d3ed426efa189a9",
    "productId": "web-mobile-7d3ed426efa189a9",
    "name": "Samsung Galaxy A37",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy A37",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-41120-samsung-galaxy-a37.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.852Z"
  },
  {
    "id": "web-mobile-3a59d18699902df1",
    "productId": "web-mobile-3a59d18699902df1",
    "name": "Samsung Galaxy A55",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy A55",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40357-samsung-galaxy-a55.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.852Z"
  },
  {
    "id": "web-mobile-005fdbbb4e0042a5",
    "productId": "web-mobile-005fdbbb4e0042a5",
    "name": "Samsung Galaxy A35",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy A35",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40358-samsung-galaxy-a35.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.852Z"
  },
  {
    "id": "web-mobile-f06e87c50a07e6c5",
    "productId": "web-mobile-f06e87c50a07e6c5",
    "name": "Samsung Galaxy S26",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy S26",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-41115-samsung-galaxy-s26.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.852Z"
  },
  {
    "id": "web-mobile-6d7e8792ab6d5d4b",
    "productId": "web-mobile-6d7e8792ab6d5d4b",
    "name": "Samsung Galaxy Z Fold7",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy Z Fold7",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40869-samsung-galaxy-z-fold7.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.853Z"
  },
  {
    "id": "web-mobile-3772570ed18659af",
    "productId": "web-mobile-3772570ed18659af",
    "name": "Xiaomi 15T Pro",
    "brand": "شیائومی",
    "model": "Xiaomi 15T Pro",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40958-xiaomi-15t-pro.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.853Z"
  },
  {
    "id": "web-mobile-334db9565efd3f2c",
    "productId": "web-mobile-334db9565efd3f2c",
    "name": "Samsung Galaxy Z Fold8",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy Z Fold8",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-41270-samsung-galaxy-z-fold8.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.853Z"
  },
  {
    "id": "web-mobile-1606242d82149c99",
    "productId": "web-mobile-1606242d82149c99",
    "name": "Samsung Galaxy Z Fold8 Ultra",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy Z Fold8 Ultra",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-41269-samsung-galaxy-z-fold8-ultra.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.853Z"
  },
  {
    "id": "web-mobile-6af6e8401f6d880c",
    "productId": "web-mobile-6af6e8401f6d880c",
    "name": "Samsung Galaxy Z Flip8",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy Z Flip8",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-41271-samsung-galaxy-z-flip8.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.854Z"
  },
  {
    "id": "web-mobile-b1790e2c32cdf2ce",
    "productId": "web-mobile-b1790e2c32cdf2ce",
    "name": "Xiaomi Poco M5s",
    "brand": "شیائومی",
    "model": "Xiaomi Poco M5s",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-39798-xiaomi-poco-m5s.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.854Z"
  },
  {
    "id": "web-mobile-3f79a36d3cad4564",
    "productId": "web-mobile-3f79a36d3cad4564",
    "name": "Xiaomi Poco C75",
    "brand": "شیائومی",
    "model": "Xiaomi Poco C75",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40606-xiaomi-poco-c75.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.854Z"
  },
  {
    "id": "web-mobile-758184b80b94b114",
    "productId": "web-mobile-758184b80b94b114",
    "name": "Xiaomi Redmi 15 4G",
    "brand": "شیائومی",
    "model": "Xiaomi Redmi 15 4G",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40888-xiaomi-redmi-15-4g.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.854Z"
  },
  {
    "id": "web-mobile-f5fe70e7a2fc88ff",
    "productId": "web-mobile-f5fe70e7a2fc88ff",
    "name": "Xiaomi Redmi 15C 4G",
    "brand": "شیائومی",
    "model": "Xiaomi Redmi 15C 4G",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40890-xiaomi-redmi-15c-4g.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.854Z"
  },
  {
    "id": "web-mobile-3657a26a277e2a57",
    "productId": "web-mobile-3657a26a277e2a57",
    "name": "Xiaomi Poco M7",
    "brand": "شیائومی",
    "model": "Xiaomi Poco M7",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40712-xiaomi-poco-m7.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.854Z"
  },
  {
    "id": "web-mobile-bbb538061adc7f06",
    "productId": "web-mobile-bbb538061adc7f06",
    "name": "Xiaomi Poco F6 Pro",
    "brand": "شیائومی",
    "model": "Xiaomi Poco F6 Pro",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40448-xiaomi-poco-f6-pro.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.854Z"
  },
  {
    "id": "web-mobile-cbe9e3fcc33531dd",
    "productId": "web-mobile-cbe9e3fcc33531dd",
    "name": "Xiaomi Poco F7 Pro",
    "brand": "شیائومی",
    "model": "Xiaomi Poco F7 Pro",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40734-xiaomi-poco-f7-pro.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.854Z"
  },
  {
    "id": "web-mobile-990bef63d6e7b0bc",
    "productId": "web-mobile-990bef63d6e7b0bc",
    "name": "Xiaomi Poco X8 Pro",
    "brand": "شیائومی",
    "model": "Xiaomi Poco X8 Pro",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-41131-xiaomi-poco-x8-pro.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.855Z"
  },
  {
    "id": "web-mobile-3d875f6dfe205f1c",
    "productId": "web-mobile-3d875f6dfe205f1c",
    "name": "Xiaomi Redmi Note 14 4G (Global)",
    "brand": "شیائومی",
    "model": "Xiaomi Redmi Note 14 4G (Global)",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-40678-xiaomi-redmi-note-14-4g-global.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.855Z"
  },
  {
    "id": "web-mobile-60d4b1cd6a3a02dd",
    "productId": "web-mobile-60d4b1cd6a3a02dd",
    "name": "Xiaomi Redmi Note 15 4G",
    "brand": "شیائومی",
    "model": "Xiaomi Redmi Note 15 4G",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-41049-xiaomi-redmi-note-15-4g.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.855Z"
  },
  {
    "id": "web-mobile-75bc80b5c6d04814",
    "productId": "web-mobile-75bc80b5c6d04814",
    "name": "Xiaomi Redmi Note 15 Pro+",
    "brand": "شیائومی",
    "model": "Xiaomi Redmi Note 15 Pro+",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.mobile.ir/phones/shops-41045-xiaomi-redmi-note-15-pro.aspx",
    "sourceId": "mobile-ir",
    "sourceUrl": "https://www.mobile.ir/phones/prices.aspx?brandid=0&duration=14&pagesize=200&price_from=-1&price_to=-1&provinceid=0&shopid=0&sort=warranty&terms=",
    "source": "web-catalog:mobile-ir",
    "observedAt": "2026-08-31T22:47:41.855Z"
  },
  {
    "id": "web-mobile-64af5163492282e7",
    "productId": "web-mobile-64af5163492282e7",
    "name": "خاکی نقره ای مشکی گوشی موبایل اپل iPhone 16 Pro Max 8GB 1TB ZA/A Dual Sim نات اکتیو",
    "brand": "اپل",
    "model": "خاکی نقره ای مشکی گوشی موبایل اپل iPhone 16 Pro Max 8GB 1TB ZA/A Dual Sim نات اکتیو",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-3106-3107-3108-iphone-16-8gb-1tb-ch-a-dual-sim/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:47.448Z"
  },
  {
    "id": "web-mobile-2fcdd54c75ad77f2",
    "productId": "web-mobile-2fcdd54c75ad77f2",
    "name": "آبی سبز سفید یاسی مشکی گوشی موبایل اپل iPhone 17 8GB 256GB Dual Sim نات اکتیو",
    "brand": "اپل",
    "model": "آبی سبز سفید یاسی مشکی گوشی موبایل اپل iPhone 17 8GB 256GB Dual Sim نات اکتیو",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-6518-6519-6520-6521-6522-iphone-17-8gb-256gb-dual-sim-not-active/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:47.449Z"
  },
  {
    "id": "web-mobile-63edb05b9f11de45",
    "productId": "web-mobile-63edb05b9f11de45",
    "name": "سرمه ای نارنجی نقره ای گوشی موبایل اپل iPhone 17 Pro Max 12GB 256GB Dual Sim نات اکتیو",
    "brand": "اپل",
    "model": "سرمه ای نارنجی نقره ای گوشی موبایل اپل iPhone 17 Pro Max 12GB 256GB Dual Sim نات اکتیو",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-6599-6600-6001-iphone-17-pro-max-12gb-256gb-dual-sim-not-active/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:47.449Z"
  },
  {
    "id": "web-mobile-b4650869d285abd0",
    "productId": "web-mobile-b4650869d285abd0",
    "name": "سبز مشکی بنفش گوشی موبایل سامسونگ Galaxy A07 6GB 128GB",
    "brand": "سامسونگ",
    "model": "سبز مشکی بنفش گوشی موبایل سامسونگ Galaxy A07 6GB 128GB",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-7792-7793-7794-galaxy-a07-6gb-128gb/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:47.449Z"
  },
  {
    "id": "web-mobile-f5c836495c0358ad",
    "productId": "web-mobile-f5c836495c0358ad",
    "name": "آبی طوسی مشکی گوشی موبایل سامسونگ Galaxy A17 6GB 128GB (ویتنام)",
    "brand": "سامسونگ",
    "model": "آبی طوسی مشکی گوشی موبایل سامسونگ Galaxy A17 6GB 128GB (ویتنام)",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-9844-9845-9846-galaxy-a17-6gb-128gb/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:47.449Z"
  },
  {
    "id": "web-mobile-f613c8df1dc5390a",
    "productId": "web-mobile-f613c8df1dc5390a",
    "name": "صورتی مشکی گوشی موبایل سامسونگ Galaxy A26 6GB 128GB",
    "brand": "سامسونگ",
    "model": "صورتی مشکی گوشی موبایل سامسونگ Galaxy A26 6GB 128GB",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-7984-7985-galaxy-a26-6gb-128gb/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:47.449Z"
  },
  {
    "id": "web-mobile-10ed5044ac0e10d1",
    "productId": "web-mobile-10ed5044ac0e10d1",
    "name": "لیمویی یاسی سفید مشکی گوشی موبایل سامسونگ Galaxy A36 8GB 256GB (2025) (ویتنام)",
    "brand": "سامسونگ",
    "model": "لیمویی یاسی سفید مشکی گوشی موبایل سامسونگ Galaxy A36 8GB 256GB (2025) (ویتنام)",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-9458-9459-9434-9435-galaxy-a36-8gb-256gb/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:47.449Z"
  },
  {
    "id": "web-mobile-0bf41687d06bb3f2",
    "productId": "web-mobile-0bf41687d06bb3f2",
    "name": "سبز طوسی صورتی مشکی گوشی موبایل سامسونگ Galaxy A56 12GB 256GB (2025) (ویتنام)",
    "brand": "سامسونگ",
    "model": "سبز طوسی صورتی مشکی گوشی موبایل سامسونگ Galaxy A56 12GB 256GB (2025) (ویتنام)",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-9760-9761-galaxy-a56-12gb-256gb/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:47.449Z"
  },
  {
    "id": "web-mobile-b7187056b1405e13",
    "productId": "web-mobile-b7187056b1405e13",
    "name": "سبز طوسی صورتی مشکی گوشی موبایل سامسونگ Galaxy A56 8GB 256GB (2025) (ویتنام)",
    "brand": "سامسونگ",
    "model": "سبز طوسی صورتی مشکی گوشی موبایل سامسونگ Galaxy A56 8GB 256GB (2025) (ویتنام)",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-10353-10354-10355-10356-galaxy-a56-12gb-256gb/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:47.449Z"
  },
  {
    "id": "web-mobile-215e3d55173b65ff",
    "productId": "web-mobile-215e3d55173b65ff",
    "name": "مشکی آبی روشن سرمه ای گوشی موبایل سامسونگ Galaxy S25 FE 8GB 256GB (ویتنام)",
    "brand": "سامسونگ",
    "model": "مشکی آبی روشن سرمه ای گوشی موبایل سامسونگ Galaxy S25 FE 8GB 256GB (ویتنام)",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-7876-7877-7878-galaxy-s25-fe-8gb-256gb/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:47.449Z"
  },
  {
    "id": "web-mobile-e5bedde7fee935ba",
    "productId": "web-mobile-e5bedde7fee935ba",
    "name": "مشکی طوسی اقیانوسی جت بلک گوشی موبایل سامسونگ Galaxy S25 Ultra 12GB 256GB (2025)",
    "brand": "سامسونگ",
    "model": "مشکی طوسی اقیانوسی جت بلک گوشی موبایل سامسونگ Galaxy S25 Ultra 12GB 256GB (2025)",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-3126-3127-3128-3129-samsung-galaxy-s25-ultra-12gb-256gb-2025/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:47.449Z"
  },
  {
    "id": "web-mobile-aab38913ca0b2e22",
    "productId": "web-mobile-aab38913ca0b2e22",
    "name": "آبی مشکی طلایی گوشی موبایل شیائومی Poco C71 4G 3GB 64GB (گلوبال)",
    "brand": "شیائومی",
    "model": "آبی مشکی طلایی گوشی موبایل شیائومی Poco C71 4G 3GB 64GB (گلوبال)",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-10916-10917-10918-poco-c71-unisoc-t7250-3gb-64gb/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:47.449Z"
  },
  {
    "id": "web-mobile-2e227c37cb0b25ae",
    "productId": "web-mobile-2e227c37cb0b25ae",
    "name": "نارنجی مشکی آبی سبز گوشی موبایل شیائومی Redmi 15C 4GB 128GB (گلوبال)",
    "brand": "شیائومی",
    "model": "نارنجی مشکی آبی سبز گوشی موبایل شیائومی Redmi 15C 4GB 128GB (گلوبال)",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-9695-9696-9699-9700-redmi-15c-4gb-128gb-global/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:47.449Z"
  },
  {
    "id": "web-mobile-e6f525d58886324b",
    "productId": "web-mobile-e6f525d58886324b",
    "name": "مشکی آبی گوشی موبایل شیائومی Redmi A3 4GB 128GB (گلوبال)",
    "brand": "شیائومی",
    "model": "مشکی آبی گوشی موبایل شیائومی Redmi A3 4GB 128GB (گلوبال)",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-9031-9032-redmi-a3-4gb-128gb-global/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:47.449Z"
  },
  {
    "id": "web-mobile-35b93010114879e0",
    "productId": "web-mobile-35b93010114879e0",
    "name": "بنفش مشکی آبی روشن لیمویی گوشی موبایل شیائومی Redmi Note 14 4G 8GB 256GB (گلوبال)",
    "brand": "شیائومی",
    "model": "بنفش مشکی آبی روشن لیمویی گوشی موبایل شیائومی Redmi Note 14 4G 8GB 256GB (گلوبال)",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-3482-3483-3484-xiaomi-redmi-note-14-4g-8gb-256gb-global/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:47.449Z"
  },
  {
    "id": "web-mobile-ada592d0b05c2ee4",
    "productId": "web-mobile-ada592d0b05c2ee4",
    "name": "مشکی آبی روشن بنفش گوشی موبایل شیائومی Redmi Note 14 Pro 4G 8GB 256GB (گلوبال)",
    "brand": "شیائومی",
    "model": "مشکی آبی روشن بنفش گوشی موبایل شیائومی Redmi Note 14 Pro 4G 8GB 256GB (گلوبال)",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-3500-3501-3502-xiaomi-redmi-note-14-pro-4g-8gb-256gb-global/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:47.449Z"
  },
  {
    "id": "web-mobile-53d47abc4e3de14e",
    "productId": "web-mobile-53d47abc4e3de14e",
    "name": "آبی سبز سفید صورتی مشکی گوشی موبایل اپل iPhone 16 8GB 128GB CH/A Dual Sim نات اکتیو",
    "brand": "اپل",
    "model": "آبی سبز سفید صورتی مشکی گوشی موبایل اپل iPhone 16 8GB 128GB CH/A Dual Sim نات اکتیو",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-3019-3020-3021-3022-3023-iphone-16-8gb-256gb-ch-a-dual-sim/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:47.449Z"
  },
  {
    "id": "web-mobile-91e74e80ee2605dc",
    "productId": "web-mobile-91e74e80ee2605dc",
    "name": "آبی سبز سفید مشکی گوشی موبایل اپل iPhone 16 8GB 256GB CH/A Dual Sim نات اکتیو",
    "brand": "اپل",
    "model": "آبی سبز سفید مشکی گوشی موبایل اپل iPhone 16 8GB 256GB CH/A Dual Sim نات اکتیو",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-2990-iphone-16-8gb-256gb-ch-a-dual-sim/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:47.449Z"
  },
  {
    "id": "web-mobile-8bc484c45c54c8af",
    "productId": "web-mobile-8bc484c45c54c8af",
    "name": "خاکی نقره ای مشکی گوشی موبایل اپل iPhone 16 Pro 8GB 256GB ZA/A Dual Sim نات اکتیو",
    "brand": "اپل",
    "model": "خاکی نقره ای مشکی گوشی موبایل اپل iPhone 16 Pro 8GB 256GB ZA/A Dual Sim نات اکتیو",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-3166-3167-3168-iphone-16-pro-8gb-256gb-ch-a-dual-sim/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:47.449Z"
  },
  {
    "id": "web-mobile-6ca27cd40da2f4be",
    "productId": "web-mobile-6ca27cd40da2f4be",
    "name": "سفید خاکی نقره ای مشکی گوشی موبایل اپل iPhone 16 Pro 8GB 512GB ZA/A Dual Sim نات اکتیو",
    "brand": "اپل",
    "model": "سفید خاکی نقره ای مشکی گوشی موبایل اپل iPhone 16 Pro 8GB 512GB ZA/A Dual Sim نات اکتیو",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-3279-3280-3281-3282-apple-iphone-16-pro-8gb-512gb-za-a-dual-sim/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:47.449Z"
  },
  {
    "id": "web-mobile-5d98ef7ed0e84f22",
    "productId": "web-mobile-5d98ef7ed0e84f22",
    "name": "خاکی نقره ای مشکی گوشی موبایل اپل iPhone 16 Pro Max 8GB 256GB ZA/A Dual Sim نات اکتیو",
    "brand": "اپل",
    "model": "خاکی نقره ای مشکی گوشی موبایل اپل iPhone 16 Pro Max 8GB 256GB ZA/A Dual Sim نات اکتیو",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-3271-3272-3273-apple-iphone-16-pro-max-8gb-256gb-za-a-dual-sim/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/page/2/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:52.124Z"
  },
  {
    "id": "web-mobile-691a9e47b7ca30db",
    "productId": "web-mobile-691a9e47b7ca30db",
    "name": "خاکی نقره ای مشکی گوشی موبایل اپل iPhone 16 Pro Max 8GB 512GB ZA/A Dual Sim نات اکتیو",
    "brand": "اپل",
    "model": "خاکی نقره ای مشکی گوشی موبایل اپل iPhone 16 Pro Max 8GB 512GB ZA/A Dual Sim نات اکتیو",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-3275-3276-3277-apple-iphone-16-pro-max-8gb-512gb-za-a-dual-sim/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/page/2/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:52.124Z"
  },
  {
    "id": "web-mobile-48c19ad9413c939d",
    "productId": "web-mobile-48c19ad9413c939d",
    "name": "آبی سفید مشکی طلایی گوشی موبایل اپل iPhone 17 Air 8GB 256GB Dual Sim نات اکتیو",
    "brand": "اپل",
    "model": "آبی سفید مشکی طلایی گوشی موبایل اپل iPhone 17 Air 8GB 256GB Dual Sim نات اکتیو",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-6661-6662-6663-6664-iapple-iphone-17-air-8gb-256gb-dual-sim-not-active/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/page/2/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:52.124Z"
  },
  {
    "id": "web-mobile-ced993e1747ed64b",
    "productId": "web-mobile-ced993e1747ed64b",
    "name": "سفید طلایی آبی گوشی موبایل سامسونگ Galaxy A06 4GB 128GB",
    "brand": "سامسونگ",
    "model": "سفید طلایی آبی گوشی موبایل سامسونگ Galaxy A06 4GB 128GB",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-3612-galaxy-a06-4gb-128gb/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/page/2/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:52.124Z"
  },
  {
    "id": "web-mobile-c86445d320af8212",
    "productId": "web-mobile-c86445d320af8212",
    "name": "سفید طلایی آبی گوشی موبایل سامسونگ Galaxy A06 4GB 64GB",
    "brand": "سامسونگ",
    "model": "سفید طلایی آبی گوشی موبایل سامسونگ Galaxy A06 4GB 64GB",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-6444-6445-6446-galaxy-a06-4gb-64gb/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/page/2/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:52.124Z"
  },
  {
    "id": "web-mobile-583dbcd64a61f540",
    "productId": "web-mobile-583dbcd64a61f540",
    "name": "آبی سفید طلایی گوشی موبایل سامسونگ Galaxy A06 6GB 128GB",
    "brand": "سامسونگ",
    "model": "آبی سفید طلایی گوشی موبایل سامسونگ Galaxy A06 6GB 128GB",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-6448-6449-6450-galaxy-a06-6gb-128gb/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/page/2/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:52.124Z"
  },
  {
    "id": "web-mobile-059a88d2aab6638e",
    "productId": "web-mobile-059a88d2aab6638e",
    "name": "گوشی موبایل سامسونگ Galaxy A15 8GB 256GB",
    "brand": "سامسونگ",
    "model": "گوشی موبایل سامسونگ Galaxy A15 8GB 256GB",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/product-dgp-3286-samsung-galaxy-a15-8gb-256gb/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/page/2/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:52.124Z"
  },
  {
    "id": "web-mobile-b0106823239d4842",
    "productId": "web-mobile-b0106823239d4842",
    "name": "سبز طوسی مشکی گوشی موبایل سامسونگ Galaxy A16 4G 4GB 128GB",
    "brand": "سامسونگ",
    "model": "سبز طوسی مشکی گوشی موبایل سامسونگ Galaxy A16 4G 4GB 128GB",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-9126-9127-9144-galaxy-a16-4g-4gb-128gb/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/page/2/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:52.124Z"
  },
  {
    "id": "web-mobile-c63ac2ce6f999f26",
    "productId": "web-mobile-c63ac2ce6f999f26",
    "name": "آبی مشکی یاسی گوشی موبایل سامسونگ Galaxy A35 8GB 256GB (ویتنام)",
    "brand": "سامسونگ",
    "model": "آبی مشکی یاسی گوشی موبایل سامسونگ Galaxy A35 8GB 256GB (ویتنام)",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-3231-3232-3233-samsung-galaxy-a35-8gb-256gb/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/page/2/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:52.124Z"
  },
  {
    "id": "web-mobile-3d4aa43885355e00",
    "productId": "web-mobile-3d4aa43885355e00",
    "name": "آبی زرد مشکی گوشی موبایل سامسونگ Galaxy A55 8GB 256GB (ویتنام)",
    "brand": "سامسونگ",
    "model": "آبی زرد مشکی گوشی موبایل سامسونگ Galaxy A55 8GB 256GB (ویتنام)",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-3193-3194-3196-samsung-galaxy-a55-8gb-256gb/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/page/2/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:52.124Z"
  },
  {
    "id": "web-mobile-d91e5d69c8fffa03",
    "productId": "web-mobile-d91e5d69c8fffa03",
    "name": "سبز مشکی گوشی موبایل شیائومی POCO C75 6GB 128GB (گلوبال)",
    "brand": "شیائومی",
    "model": "سبز مشکی گوشی موبایل شیائومی POCO C75 6GB 128GB (گلوبال)",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-6354-6351-poco-c75-6gb-128gb-global/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/page/2/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:52.124Z"
  },
  {
    "id": "web-mobile-04c6c3292a1fe74c",
    "productId": "web-mobile-04c6c3292a1fe74c",
    "name": "مشکی آبی گوشی موبایل شیائومی POCO M6 Pro 8GB 256GB (گلوبال)",
    "brand": "شیائومی",
    "model": "مشکی آبی گوشی موبایل شیائومی POCO M6 Pro 8GB 256GB (گلوبال)",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-8815-8816-xiaomi-poco-m6-pro-8gb-256gb-global/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/page/2/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:52.124Z"
  },
  {
    "id": "web-mobile-925148ae0c9738b2",
    "productId": "web-mobile-925148ae0c9738b2",
    "name": "سبز نقره ای گوشی موبایل شیائومی POCO X7 5G 12GB 512GB (گلوبال)",
    "brand": "شیائومی",
    "model": "سبز نقره ای گوشی موبایل شیائومی POCO X7 5G 12GB 512GB (گلوبال)",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-8966-8967-poco-x7-5g-12gb-512gb-global/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/page/2/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:52.124Z"
  },
  {
    "id": "web-mobile-adb62c5d6cd35d6c",
    "productId": "web-mobile-adb62c5d6cd35d6c",
    "name": "مشکی طلایی گوشی موبایل شیائومی Redmi 13 8GB 256GB (گلوبال)",
    "brand": "شیائومی",
    "model": "مشکی طلایی گوشی موبایل شیائومی Redmi 13 8GB 256GB (گلوبال)",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-9336-9337-redmi-13-8gb-256gb-global/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/page/2/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:52.124Z"
  },
  {
    "id": "web-mobile-254de582b7867d50",
    "productId": "web-mobile-254de582b7867d50",
    "name": "آبی مشکی گوشی موبایل شیائومی Redmi A3 Pro 4G 4GB 128GB (گلوبال)",
    "brand": "شیائومی",
    "model": "آبی مشکی گوشی موبایل شیائومی Redmi A3 Pro 4G 4GB 128GB (گلوبال)",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-10822-10823-redmi-a3-pro-helio-g81-ultra-4gb-128gb-6-88/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/page/2/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:52.124Z"
  },
  {
    "id": "web-mobile-e7a80e5ceef17aac",
    "productId": "web-mobile-e7a80e5ceef17aac",
    "name": "طلایی مشکی آبی روشن گوشی موبایل شیائومی Redmi A5 3GB 64GB (گلوبال)",
    "brand": "شیائومی",
    "model": "طلایی مشکی آبی روشن گوشی موبایل شیائومی Redmi A5 3GB 64GB (گلوبال)",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-7738-739-7740-redmi-a5-3gb-64gb-global/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/page/2/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:52.124Z"
  },
  {
    "id": "web-mobile-2cb536dc7eda625f",
    "productId": "web-mobile-2cb536dc7eda625f",
    "name": "مشکی آبی روشن بنفش گوشی موبایل شیائومی Redmi Note 14 Pro 4G 12GB 512GB (گلوبال)",
    "brand": "شیائومی",
    "model": "مشکی آبی روشن بنفش گوشی موبایل شیائومی Redmi Note 14 Pro 4G 12GB 512GB (گلوبال)",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-3514-3515-xiaomi-redmi-note-14-pro-4g-12gb-512gb-global/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/page/2/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:52.124Z"
  },
  {
    "id": "web-mobile-47d900cab32567da",
    "productId": "web-mobile-47d900cab32567da",
    "name": "مشکی بنفش آبی گوشی موبایل شیائومی Redmi Note 14 Pro 5G 12GB 512GB (گلوبال)",
    "brand": "شیائومی",
    "model": "مشکی بنفش آبی گوشی موبایل شیائومی Redmi Note 14 Pro 5G 12GB 512GB (گلوبال)",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-3465-3466-3467-xiaomi-redmi-note-14-pro-5g-12gb-512gb-global/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/page/2/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:52.124Z"
  },
  {
    "id": "web-mobile-989fd9b537503f34",
    "productId": "web-mobile-989fd9b537503f34",
    "name": "مشکی بنفش آبی گوشی موبایل شیائومی Redmi Note 14 Pro 5G 8GB 256GB (گلوبال)",
    "brand": "شیائومی",
    "model": "مشکی بنفش آبی گوشی موبایل شیائومی Redmi Note 14 Pro 5G 8GB 256GB (گلوبال)",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-3478-3479-3480-xiaomi-redmi-note-14-pro-5g-8gb-256gb-global/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/page/2/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:52.124Z"
  },
  {
    "id": "web-mobile-e0ebaa93564bbf3d",
    "productId": "web-mobile-e0ebaa93564bbf3d",
    "name": "مشکی بنفش آبی گوشی موبایل شیائومی Redmi Note 14 Pro Plus 5G 12GB 512GB (گلوبال)",
    "brand": "شیائومی",
    "model": "مشکی بنفش آبی گوشی موبایل شیائومی Redmi Note 14 Pro Plus 5G 12GB 512GB (گلوبال)",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-3446-3447-3441-xiaomi-redmi-note-14-pro-plus-5g-12gb-512gb-global/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/page/2/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:52.124Z"
  },
  {
    "id": "web-mobile-15d2bae42d6e76b6",
    "productId": "web-mobile-15d2bae42d6e76b6",
    "name": "مشکی بنفش آبی گوشی موبایل شیائومی Redmi Note 14 Pro Plus 5G 8GB 256GB (گلوبال)",
    "brand": "شیائومی",
    "model": "مشکی بنفش آبی گوشی موبایل شیائومی Redmi Note 14 Pro Plus 5G 8GB 256GB (گلوبال)",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://digizo.shop/product/dgp-3460-3461-3462-xiaomi-redmi-note-14-pro-plus-5g-8gb-256gb-global/",
    "sourceId": "digizo",
    "sourceUrl": "https://digizo.shop/product-category/mobile/page/3/",
    "source": "web-catalog:digizo",
    "observedAt": "2026-08-31T22:47:55.208Z"
  },
  {
    "id": "web-mobile-9d339ab00650458e",
    "productId": "web-mobile-9d339ab00650458e",
    "name": "Xiaomi Poco F7 Pro 12 512GB 5G",
    "brand": "شیائومی",
    "model": "Xiaomi Poco F7 Pro 12 512GB 5G",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.bprshop.com/product/12945-Xiaomi-Poco-F7-Pro-12-512",
    "sourceId": "bprshop",
    "sourceUrl": "https://www.bprshop.com/mobile",
    "source": "web-catalog:bprshop",
    "observedAt": "2026-08-31T22:47:58.245Z"
  },
  {
    "id": "web-mobile-89d10a412be81fa2",
    "productId": "web-mobile-89d10a412be81fa2",
    "name": "Xiaomi Redmi Note 14 Pro 12 512GB 4G",
    "brand": "شیائومی",
    "model": "Xiaomi Redmi Note 14 Pro 12 512GB 4G",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.bprshop.com/product/12943-Xiaomi-Note-14-Pro-12-512-4G",
    "sourceId": "bprshop",
    "sourceUrl": "https://www.bprshop.com/mobile",
    "source": "web-catalog:bprshop",
    "observedAt": "2026-08-31T22:47:58.245Z"
  },
  {
    "id": "web-mobile-88539d3edfd06105",
    "productId": "web-mobile-88539d3edfd06105",
    "name": "Xiaomi Redmi Note 14 Pro 12 512GB 5G",
    "brand": "شیائومی",
    "model": "Xiaomi Redmi Note 14 Pro 12 512GB 5G",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.bprshop.com/product/12942-Xiaomi-Note-14-Pro-12-512",
    "sourceId": "bprshop",
    "sourceUrl": "https://www.bprshop.com/mobile",
    "source": "web-catalog:bprshop",
    "observedAt": "2026-08-31T22:47:58.245Z"
  },
  {
    "id": "web-mobile-e92490ac7d6e5556",
    "productId": "web-mobile-e92490ac7d6e5556",
    "name": "Xiaomi Poco X7 8 256GB 5G",
    "brand": "شیائومی",
    "model": "Xiaomi Poco X7 8 256GB 5G",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.bprshop.com/product/12940-Xiaomi-Poco-X7-8-256",
    "sourceId": "bprshop",
    "sourceUrl": "https://www.bprshop.com/mobile",
    "source": "web-catalog:bprshop",
    "observedAt": "2026-08-31T22:47:58.245Z"
  },
  {
    "id": "web-mobile-5e568e7546d03654",
    "productId": "web-mobile-5e568e7546d03654",
    "name": "Xiaomi Poco X7 Pro 12 512GB 5G",
    "brand": "شیائومی",
    "model": "Xiaomi Poco X7 Pro 12 512GB 5G",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.bprshop.com/product/12938-Xiaomi-Poco-X7-Pro-12-512",
    "sourceId": "bprshop",
    "sourceUrl": "https://www.bprshop.com/mobile",
    "source": "web-catalog:bprshop",
    "observedAt": "2026-08-31T22:47:58.245Z"
  },
  {
    "id": "web-mobile-52eec7474332a8a5",
    "productId": "web-mobile-52eec7474332a8a5",
    "name": "Samsung Galaxy A06 4 128 4G",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy A06 4 128 4G",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.bprshop.com/product/12935-Samsung-A06-4-128",
    "sourceId": "bprshop",
    "sourceUrl": "https://www.bprshop.com/mobile",
    "source": "web-catalog:bprshop",
    "observedAt": "2026-08-31T22:47:58.245Z"
  },
  {
    "id": "web-mobile-2ef4a854480c0492",
    "productId": "web-mobile-2ef4a854480c0492",
    "name": "Samsung Galaxy A07 4 64 4G",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy A07 4 64 4G",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.bprshop.com/product/12933-Samsung-A07-4-64",
    "sourceId": "bprshop",
    "sourceUrl": "https://www.bprshop.com/mobile",
    "source": "web-catalog:bprshop",
    "observedAt": "2026-08-31T22:47:58.245Z"
  },
  {
    "id": "web-mobile-9811052e5831f6f9",
    "productId": "web-mobile-9811052e5831f6f9",
    "name": "Samsung Galaxy A07 4 128 4G",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy A07 4 128 4G",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.bprshop.com/product/12932-Samsung-Galaxy-A07-4-128",
    "sourceId": "bprshop",
    "sourceUrl": "https://www.bprshop.com/mobile",
    "source": "web-catalog:bprshop",
    "observedAt": "2026-08-31T22:47:58.245Z"
  },
  {
    "id": "web-mobile-95be281bd40b2069",
    "productId": "web-mobile-95be281bd40b2069",
    "name": "Samsung Galaxy A07 6 128 4G",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy A07 6 128 4G",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.bprshop.com/product/12931-Samsung-A07-6-128",
    "sourceId": "bprshop",
    "sourceUrl": "https://www.bprshop.com/mobile",
    "source": "web-catalog:bprshop",
    "observedAt": "2026-08-31T22:47:58.245Z"
  },
  {
    "id": "web-mobile-493cc3d7fc5e0c4d",
    "productId": "web-mobile-493cc3d7fc5e0c4d",
    "name": "Samsung Galaxy A16 4 128 4G",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy A16 4 128 4G",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.bprshop.com/product/12929-Samsung-A16-4-128",
    "sourceId": "bprshop",
    "sourceUrl": "https://www.bprshop.com/mobile",
    "source": "web-catalog:bprshop",
    "observedAt": "2026-08-31T22:47:58.245Z"
  },
  {
    "id": "web-mobile-28e50df4ae0c29c7",
    "productId": "web-mobile-28e50df4ae0c29c7",
    "name": "Samsung Galaxy A17 4 128 4G",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy A17 4 128 4G",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.bprshop.com/product/12928-Samsung-A17-4-128",
    "sourceId": "bprshop",
    "sourceUrl": "https://www.bprshop.com/mobile",
    "source": "web-catalog:bprshop",
    "observedAt": "2026-08-31T22:47:58.245Z"
  },
  {
    "id": "web-mobile-7cc711049aef9728",
    "productId": "web-mobile-7cc711049aef9728",
    "name": "Samsung Galaxy A17 8 256 4G",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy A17 8 256 4G",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.bprshop.com/product/12927-Samsung-A17-8-256",
    "sourceId": "bprshop",
    "sourceUrl": "https://www.bprshop.com/mobile",
    "source": "web-catalog:bprshop",
    "observedAt": "2026-08-31T22:47:58.245Z"
  },
  {
    "id": "web-mobile-d0d351e60fadf08b",
    "productId": "web-mobile-d0d351e60fadf08b",
    "name": "Samsung Galaxy A17 6 128 4G",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy A17 6 128 4G",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.bprshop.com/product/12926-Samsung-A17-6-128",
    "sourceId": "bprshop",
    "sourceUrl": "https://www.bprshop.com/mobile",
    "source": "web-catalog:bprshop",
    "observedAt": "2026-08-31T22:47:58.245Z"
  },
  {
    "id": "web-mobile-35a23e95fda75300",
    "productId": "web-mobile-35a23e95fda75300",
    "name": "Samsung Galaxy A26 6 128 5G",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy A26 6 128 5G",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.bprshop.com/product/12925-Samsung-A26-6-128",
    "sourceId": "bprshop",
    "sourceUrl": "https://www.bprshop.com/mobile",
    "source": "web-catalog:bprshop",
    "observedAt": "2026-08-31T22:47:58.245Z"
  },
  {
    "id": "web-mobile-602f9ea6e92b451b",
    "productId": "web-mobile-602f9ea6e92b451b",
    "name": "Samsung Galaxy A26 8 256 5G",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy A26 8 256 5G",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.bprshop.com/product/12924-Samsung-A26-8-256",
    "sourceId": "bprshop",
    "sourceUrl": "https://www.bprshop.com/mobile",
    "source": "web-catalog:bprshop",
    "observedAt": "2026-08-31T22:47:58.245Z"
  },
  {
    "id": "web-mobile-c0c76cbbec6d5303",
    "productId": "web-mobile-c0c76cbbec6d5303",
    "name": "Samsung Galaxy A36 8 128 5G",
    "brand": "سامسونگ",
    "model": "Samsung Galaxy A36 8 128 5G",
    "category": "mobile",
    "price": 0,
    "currency": "IRR",
    "availability": "unknown",
    "productUrl": "https://www.bprshop.com/product/12923-Samsung-A36-8-128",
    "sourceId": "bprshop",
    "sourceUrl": "https://www.bprshop.com/mobile",
    "source": "web-catalog:bprshop",
    "observedAt": "2026-08-31T22:47:58.245Z"
  }
];
