// DigiYar V5.1 Price / Availability Engine
// Refreshes an existing catalog record from its source URL. It never invents a price or stock state.
export const PRICE_TTL_MS = 6 * 60 * 60 * 1000;
const UA='DigiYar-PriceEngine/5.1';
const num=s=>{const m=String(s??'').replace(/[٬,\s]/g,'').match(/\d+/);return m?Number(m[0]):0};
const fresh=t=>{const x=Date.parse(t||'');return Number.isFinite(x)&&(Date.now()-x)<=PRICE_TTL_MS};
const stock=t=>{const s=String(t||'');if(/ناموجود|در انبار موجود نمی باشد|تمام شده|out of stock|unavailable/i.test(s))return'out_of_stock';if(/موجود در انبار|موجود|in stock/i.test(s))return'in_stock';return'unknown'};
function walk(x,out){if(!x)return;if(Array.isArray(x)){x.forEach(v=>walk(v,out));return}if(typeof x!=='object')return;const t=Array.isArray(x['@type'])?x['@type'].join(' '):String(x['@type']||'');if(/product/i.test(t)&&x.name){const o=Array.isArray(x.offers)?x.offers[0]:x.offers||{};out.push({name:x.name,price:num(o.price||x.price),currency:o.priceCurrency||'IRR',availability:o.availability||x.availability||'unknown',url:x.url||''})}Object.values(x).forEach(v=>v&&typeof v==='object'&&walk(v,out))}
function jsonLd(html){const out=[],re=/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;let m;while((m=re.exec(html))){try{walk(JSON.parse(m[1]),out)}catch{}}return out}
export async function refreshOffer(offer,{now=new Date().toISOString()}={}){if(!offer?.productUrl)return{...offer,refreshStatus:'no_url'};try{const r=await fetch(offer.productUrl,{redirect:'follow',headers:{'user-agent':UA,'accept':'text/html,application/xhtml+xml,application/json','accept-language':'fa-IR,fa;q=0.9'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const html=await r.text();const products=jsonLd(html);const p=products[0];if(!p)return{...offer,availability:'unknown',refreshStatus:'no_product_schema',observedAt:now,stale:false};return{...offer,price:p.price||0,currency:p.currency||offer.currency||'IRR',availability:stock(p.availability),productUrl:p.url||offer.productUrl,observedAt:now,stale:false,refreshStatus:'ok'}}catch(error){return{...offer,stale:true,refreshStatus:'error',refreshError:String(error)}}}
export async function refreshProduct(product,opts={}){const offers=await Promise.all((product.offers||[]).map(o=>refreshOffer(o,opts)));return{...product,offers,available:offers.some(o=>!o.stale&&o.availability==='in_stock'),bestPrice:Math.min(...offers.filter(o=>!o.stale&&o.availability==='in_stock'&&o.price>0).map(o=>o.price),Infinity)}}
export function freshness(offer){return{fresh:fresh(offer?.observedAt),observedAt:offer?.observedAt||null,ttlMs:PRICE_TTL_MS}}
