// DigiYar V5.1 Product Index Seed
// Canonical product records for Search Core. Prices are benchmark seed values, not live market quotes.
export const PRODUCT_SEED = [
  {productId:'seed-mobile-samsung-s25-ultra',name:'گوشی سامسونگ Galaxy S25 Ultra',brand:'سامسونگ',model:'Galaxy S25 Ultra',category:'mobile',price:85000000,currency:'IRR',availability:'unknown',productUrl:'https://www.samsung.com/global/galaxy/galaxy-s25-ultra/',storeId:'catalog',storeName:'DigiYar Index',source:'benchmark-seed'},
  {productId:'seed-mobile-samsung-s24-fe',name:'گوشی سامسونگ Galaxy S24 FE',brand:'سامسونگ',model:'Galaxy S24 FE',category:'mobile',price:45000000,currency:'IRR',availability:'unknown',productUrl:'https://www.samsung.com/global/galaxy/galaxy-s24-fe/',storeId:'catalog',storeName:'DigiYar Index',source:'benchmark-seed'},
  {productId:'seed-mobile-samsung-a56',name:'گوشی سامسونگ Galaxy A56',brand:'سامسونگ',model:'Galaxy A56',category:'mobile',price:30000000,currency:'IRR',availability:'unknown',productUrl:'https://www.samsung.com/global/smartphones/galaxy-a/galaxy-a56-5g/',storeId:'catalog',storeName:'DigiYar Index',source:'benchmark-seed'},
  {productId:'seed-mobile-xiaomi-redmi-note-14-pro',name:'گوشی شیائومی Redmi Note 14 Pro',brand:'شیائومی',model:'Redmi Note 14 Pro',category:'mobile',price:25000000,currency:'IRR',availability:'unknown',productUrl:'https://www.mi.com/global/product/redmi-note-14-pro/',storeId:'catalog',storeName:'DigiYar Index',source:'benchmark-seed'},
  {productId:'seed-mobile-xiaomi-poco-x7-pro',name:'گوشی شیائومی Poco X7 Pro',brand:'شیائومی',model:'Poco X7 Pro',category:'mobile',price:28000000,currency:'IRR',availability:'unknown',productUrl:'https://www.po.co/global/product/poco-x7-pro/',storeId:'catalog',storeName:'DigiYar Index',source:'benchmark-seed'},
  {productId:'seed-mobile-xiaomi-15-ultra',name:'گوشی شیائومی 15 Ultra',brand:'شیائومی',model:'15 Ultra',category:'mobile',price:90000000,currency:'IRR',availability:'unknown',productUrl:'https://www.mi.com/global/product/xiaomi-15-ultra/',storeId:'catalog',storeName:'DigiYar Index',source:'benchmark-seed'},
  {productId:'seed-mobile-apple-iphone-16-pro-max',name:'گوشی آیفون 16 پرو مکس',brand:'اپل',model:'iPhone 16 Pro Max',category:'mobile',price:95000000,currency:'IRR',availability:'unknown',productUrl:'https://www.apple.com/iphone-16-pro/',storeId:'catalog',storeName:'DigiYar Index',source:'benchmark-seed'},
  {productId:'seed-mobile-apple-iphone-16-pro',name:'گوشی آیفون 16 پرو',brand:'اپل',model:'iPhone 16 Pro',category:'mobile',price:85000000,currency:'IRR',availability:'unknown',productUrl:'https://www.apple.com/iphone-16-pro/',storeId:'catalog',storeName:'DigiYar Index',source:'benchmark-seed'},
  {productId:'seed-mobile-apple-iphone-15',name:'گوشی آیفون 15',brand:'اپل',model:'iPhone 15',category:'mobile',price:55000000,currency:'IRR',availability:'unknown',productUrl:'https://www.apple.com/iphone-15/',storeId:'catalog',storeName:'DigiYar Index',source:'benchmark-seed'},
  {productId:'seed-mobile-honor-magic7-pro',name:'گوشی آنر Magic7 Pro',brand:'آنر',model:'Magic7 Pro',category:'mobile',price:65000000,currency:'IRR',availability:'unknown',productUrl:'https://www.honor.com/global/phones/honor-magic7-pro/',storeId:'catalog',storeName:'DigiYar Index',source:'benchmark-seed'},
  {productId:'seed-laptop-lenovo-ideapad-slim-5',name:'لپ تاپ لنوو IdeaPad Slim 5',brand:'لنوو',model:'IdeaPad Slim 5',category:'laptop',price:35000000,currency:'IRR',availability:'unknown',productUrl:'https://www.lenovo.com/us/en/c/laptops/ideapad/',storeId:'catalog',storeName:'DigiYar Index',source:'benchmark-seed'},
  {productId:'seed-laptop-lenovo-loq-15',name:'لپ تاپ لنوو LOQ 15',brand:'لنوو',model:'LOQ 15',category:'laptop',price:55000000,currency:'IRR',availability:'unknown',productUrl:'https://www.lenovo.com/us/en/c/laptops/loq/',storeId:'catalog',storeName:'DigiYar Index',source:'benchmark-seed'},
  {productId:'seed-laptop-asus-rog-strix-g16',name:'لپ تاپ ایسوس ROG Strix G16',brand:'ایسوس',model:'ROG Strix G16',category:'laptop',price:85000000,currency:'IRR',availability:'unknown',productUrl:'https://rog.asus.com/laptops/rog-strix/rog-strix-g16-2025/',storeId:'catalog',storeName:'DigiYar Index',source:'benchmark-seed'},
  {productId:'seed-laptop-asus-vivobook-s15',name:'لپ تاپ ایسوس Vivobook S15',brand:'ایسوس',model:'Vivobook S15',category:'laptop',price:45000000,currency:'IRR',availability:'unknown',productUrl:'https://www.asus.com/laptops/for-home/vivobook/',storeId:'catalog',storeName:'DigiYar Index',source:'benchmark-seed'},
  {productId:'seed-laptop-acer-aspire-5',name:'لپ تاپ ایسر Aspire 5',brand:'ایسر',model:'Aspire 5',category:'laptop',price:38000000,currency:'IRR',availability:'unknown',productUrl:'https://www.acer.com/us-en/laptops/aspire/aspire-5',storeId:'catalog',storeName:'DigiYar Index',source:'benchmark-seed'},
  {productId:'seed-laptop-hp-omnibook-5',name:'لپ تاپ اچ پی OmniBook 5',brand:'اچ‌پی',model:'OmniBook 5',category:'laptop',price:50000000,currency:'IRR',availability:'unknown',productUrl:'https://www.hp.com/us-en/laptops-and-2-in-1s.html',storeId:'catalog',storeName:'DigiYar Index',source:'benchmark-seed'},
  {productId:'seed-laptop-dell-inspiron-15',name:'لپ تاپ دل Inspiron 15',brand:'دل',model:'Inspiron 15',category:'laptop',price:42000000,currency:'IRR',availability:'unknown',productUrl:'https://www.dell.com/en-us/shop/dell-laptops-and-2-in-1-pcs/scr/laptops',storeId:'catalog',storeName:'DigiYar Index',source:'benchmark-seed'},
  {productId:'seed-laptop-apple-macbook-air-m3',name:'مک بوک ایر M3',brand:'اپل',model:'MacBook Air M3',category:'laptop',price:75000000,currency:'IRR',availability:'unknown',productUrl:'https://www.apple.com/macbook-air/',storeId:'catalog',storeName:'DigiYar Index',source:'benchmark-seed'},
  {productId:'seed-laptop-apple-macbook-pro-m4',name:'مک بوک پرو M4',brand:'اپل',model:'MacBook Pro M4',category:'laptop',price:120000000,currency:'IRR',availability:'unknown',productUrl:'https://www.apple.com/macbook-pro/',storeId:'catalog',storeName:'DigiYar Index',source:'benchmark-seed'},
  {productId:'seed-laptop-asus-tuf-a15',name:'لپ تاپ ایسوس TUF Gaming A15',brand:'ایسوس',model:'TUF Gaming A15',category:'laptop',price:65000000,currency:'IRR',availability:'unknown',productUrl:'https://www.asus.com/laptops/for-gaming/tuf-gaming/',storeId:'catalog',storeName:'DigiYar Index',source:'benchmark-seed'}
];

export const MOBILE_SEED = PRODUCT_SEED.filter(p=>p.category==='mobile');
export const LAPTOP_SEED = PRODUCT_SEED.filter(p=>p.category==='laptop');
