// DigiYar V5.1 Search Core — provider-agnostic
const STOP=new Set(['برای','با','و','در','از','یک','این','آن','می','به','تومان','تومن','میلیون','میلیارد','هزار']);
const BRANDS=['سامسونگ','شیائومی','اپل','آیفون','هواوی','آنر','لنوو','ایسوس','اچ‌پی','hp','dell','acer'];
export const ProductSchema={id:'',name:'',brand:'',model:'',category:'',attributes:{},offers:[]};
export const OfferSchema={id:'',productId:'',storeId:'',storeName:'',price:0,currency:'IRR',availability:'unknown',productUrl:'',affiliateUrl:'',source:'',fetchedAt:''};
export function normalize(s=''){return String(s).toLowerCase().replace(/[يى]/g,'ی').replace(/ك/g,'ک').replace(/[٬,]/g,'').replace(/\s+/g,' ').trim()}
export function moneyValue(n,u=''){const x=Number(n);if(!u||u==='تومان')return x;if(u==='هزار')return x*1e3;if(u==='میلیون')return x*1e6;if(u==='میلیارد')return x*1e9;return x}
export function parsePriceConstraint(q=''){const r=normalize(q);const range=r.match(/(\d+(?:\.\d+)?)\s*(?:تا|-|–)\s*(\d+(?:\.\d+)?)\s*(میلیون|میلیارد|هزار|تومان)?/i),max=r.match(/(?:زیر|کمتر از|حداکثر|تا)\s*(\d+(?:\.\d+)?)\s*(میلیون|میلیارد|هزار|تومان)?/i),min=r.match(/(?:بالای|بیشتر از|حداقل)\s*(\d+(?:\.\d+)?)\s*(میلیون|میلیارد|هزار|تومان)?/i);if(range)return{minPrice:moneyValue(range[1],range[3]),maxPrice:moneyValue(range[2],range[3]),currency:'IRR'};return{minPrice:min?moneyValue(min[1],min[2]):null,maxPrice:max?moneyValue(max[1],max[2]):null,currency:'IRR'}}
export function parseQuery(input=''){const raw=String(input).trim(),normalized=normalize(raw),tokens=normalized.split(' ').filter(Boolean),brands=tokens.filter(t=>BRANDS.includes(t)),price=parsePriceConstraint(normalized),keywords=tokens.filter(t=>!STOP.has(t)&&!/^\d+(?:\.\d+)?$/.test(t));return{raw,normalized,tokens,brands,price,keywords}}
export function normalizeOffer(o={}){return{id:String(o.id||o.offerId||o.productId||''),productId:String(o.productId||o.id||''),storeId:String(o.storeId||o.store||''),storeName:o.storeName||o.store||'',name:o.name||o.productName||'',brand:o.brand||'',price:Number(o.price||o.sellingPrice||0),currency:o.currency||'IRR',availability:o.availability||(o.available===true?'in_stock':o.available===false?'out_of_stock':'unknown'),productUrl:o.productUrl||o.url||'',affiliateUrl:o.affiliateUrl||'',source:o.source||'',fetchedAt:o.fetchedAt||new Date().toISOString()}}
export function hardFilter(offers=[],constraints={}){return offers.map(normalizeOffer).filter(o=>{if(!o.productId||!o.productUrl||/\/search(?:\/|\?|$)/i.test(o.productUrl))return false;if(constraints.minPrice!=null&&(!o.price||o.price<constraints.minPrice))return false;if(constraints.maxPrice!=null&&(!o.price||o.price>constraints.maxPrice))return false;if(constraints.available===true&&o.availability==='out_of_stock')return false;return true})}
export function scoreOffer(o,q={}){const n=normalize(o.name),words=q.keywords||[];let s=0;for(const w of words)if(n.includes(normalize(w)))s+=10;if((q.brands||[]).some(b=>n.includes(normalize(b))))s+=30;if(o.availability==='in_stock')s+=8;if(o.price>0)s+=3;if(o.productUrl)s+=10;if(o.affiliateUrl)s+=2;return s}
export function rankOffers(offers=[],query={}){return hardFilter(offers,query.price||{}).map(o=>({...o,score:scoreOffer(o,query)})).sort((a,b)=>b.score-a.score||(a.price||Infinity)-(b.price||Infinity))}
export function selectBestOffer(offers=[],query={}){return rankOffers(offers,query)[0]||null}
export function groupProducts(offers=[]){const m=new Map();for(const o of offers){const x=normalizeOffer(o),k=x.productId||normalize(x.name);if(!k)continue;if(!m.has(k))m.set(k,{...ProductSchema,id:k,name:x.name,offers:[]});m.get(k).offers.push(x)}return[...m.values()]}
