// DigiYar V5.1 — Housh Yar offer-aware Product Search UI
const affiliateConfig={digikala:{name:'دیجی‌کالا',affiliateLink:'https://aflo.ir/TrvNHEN8',logo:'🛒',color:'#ef4056'},snappshop:{name:'اسنپ‌شاپ',affiliateLink:'https://aflo.ir/YPN05dL7',logo:'🛍️',color:'#00d170'}};
let searchTimeout;
function esc(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]));}
function affiliateUrl(store,target){const cfg=affiliateConfig[store];if(!cfg||!target)return target||'';return `${cfg.affiliateLink}?p=${encodeURIComponent(target)}`;}
function bestOffer(p){const offers=(p.offers||[]).filter(o=>o.available!==false&&Number.isFinite(Number(o.price))&&Number(o.price)>0);return offers.sort((a,b)=>Number(a.price)-Number(b.price))[0]||null;}
function toman(v){return Math.round(Number(v)/10).toLocaleString('fa-IR')+' تومان';}
async function searchProducts(query){const resultsDiv=document.getElementById('searchResults');if(!resultsDiv)return;showLoading();try{const index=await DigiYarInternalSearch.loadIndex();const products=DigiYarInternalSearch.search(query,index);if(!products.length){resultsDiv.innerHTML=`<div class="search-note"><p>برای «${esc(query)}» در فهرست فعلی دیجی‌یار نتیجه‌ای پیدا نشد.</p></div>`;return;}resultsDiv.innerHTML=`<h3 style="margin-bottom:10px;color:#333;text-align:center">نتایج هوش‌یار برای «${esc(query)}»</h3><p style="color:#666;font-size:13px;margin-bottom:15px;text-align:center">نتایج از پایگاه محصولات داخلی دیجی‌یار</p><div class="store-buttons">${products.map(renderProduct).join('')}</div><div class="search-note"><p>💡 قیمت‌ها از Offer فروشگاه‌ها خوانده شده و ارزان‌ترین پیشنهاد متصل نمایش داده می‌شود.</p></div>`;}catch(e){console.error('DigiYar index search:',e);resultsDiv.innerHTML='<div class="search-note"><p>پایگاه محصولات دیجی‌یار در دسترس نیست. دوباره تلاش کنید.</p></div>';}}
function renderProduct(p){const offer=bestOffer(p);const cfg=offer&&affiliateConfig[offer.store]?affiliateConfig[offer.store]:{name:'فروشگاه',logo:'🛍️',color:'#667eea'};const target=offer?.productUrl||offer?.url||'';const url=affiliateUrl(offer?.store,target);const attrs=Object.entries(p.attributes||{}).slice(0,4).map(([k,v])=>`${esc(k)}: ${esc(v)}`).join(' · ');const price=offer?toman(offer.price):'قیمت موجود نیست';return `<div class="store-card"><div class="store-logo" style="background:${cfg.color}">${cfg.logo}</div><div class="store-info"><h3>${esc(p.name)}</h3><p>${esc(p.brand||'')} · ${esc(p.category==='mobile'?'موبایل':p.category==='laptop'?'لپ‌تاپ':p.category||'محصول')}</p><p><strong>${price}</strong> · ${esc(cfg.name)}</p><p class="store-features">${attrs||'اطلاعات محصول موجود است'}</p></div>${url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer" class="store-button" style="background:${cfg.color}">مشاهده و خرید</a>`:'<span class="store-button" style="background:#999">فروشنده متصل نیست</span>'}</div>`;}
function showLoading(){const el=document.getElementById('searchResults');if(el)el.innerHTML='<div class="loading"><div class="spinner"></div><p>در حال جستجو در پایگاه دیجی‌یار...</p></div>';}
function handleSearchInput(query){clearTimeout(searchTimeout);if(query.trim().length<3)return;searchTimeout=setTimeout(()=>searchProducts(query.trim()),300);}
function handleSearchKey(event){if(event.key==='Enter'){event.preventDefault();performSmartSearch();}}
function performSmartSearch(){const input=document.getElementById('smartSearchInput');const query=input?.value.trim();if(!query)return alert('لطفاً نام محصول را وارد کنید');searchProducts(query);}
function quickSearch(term){const input=document.getElementById('smartSearchInput');if(input)input.value=term;performSmartSearch();}
