// DigiYar V5 — Housh Yar unified product search
const affiliateConfig={digikala:{name:'دیجی‌کالا',affiliateLink:'https://aflo.ir/TrvNHEN8',logo:'🛒',color:'#ef4056'},snappshop:{name:'اسنپ‌شاپ',affiliateLink:'https://aflo.ir/YPN05dL7',logo:'🛍️',color:'#00d170'}};
const SEARCH_API='https://digiyar-v5.petromosi.workers.dev/api/search';
let searchTimeout;
function esc(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]));}
function getProductUrl(p){return p.affiliateUrl||p.productUrl||p.url||'';}
function getAffiliateUrl(p){const target=getProductUrl(p);if(!target)return '';const cfg=affiliateConfig[p.store];return cfg?`${cfg.affiliateLink}?p=${encodeURIComponent(target)}`:target;}
function showLoading(){const el=document.getElementById('searchResults');if(el)el.innerHTML='<div class="loading"><div class="spinner"></div><p>در حال پیدا کردن محصولات واقعی...</p></div>';}
async function searchProducts(query){const el=document.getElementById('searchResults');if(!el)return;showLoading();try{const response=await fetch(`${SEARCH_API}?q=${encodeURIComponent(query)}`);if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json();if(!data.success||!Array.isArray(data.results)||!data.results.length){el.innerHTML=`<div class="search-note"><p>برای «${esc(query)}» محصولی پیدا نشد. لطفاً عبارت دیگری را امتحان کنید.</p></div>`;return;}el.innerHTML=`<h3 style="margin-bottom:10px;color:#333;text-align:center">نتایج واقعی «${esc(query)}»</h3><p style="color:#666;font-size:13px;margin-bottom:15px;text-align:center">محصولات پیدا شده از فروشگاه‌های متصل</p><div class="store-buttons">${data.results.map(renderProduct).join('')}</div><div class="search-note"><p>💡 لینک هر گزینه به همان محصول در فروشگاه هدایت می‌شود.</p></div>`;}catch(error){console.error('Housh Yar search error:',error);el.innerHTML='<div class="search-note"><p>اتصال به جستجوی زنده برقرار نشد. دوباره تلاش کنید.</p></div>';}}
function renderProduct(p){const cfg=affiliateConfig[p.store]||{name:p.storeName||'فروشگاه',logo:'🛍️',color:'#667eea'};const url=getAffiliateUrl(p);return `<div class="store-card"><div class="store-logo" style="background:${cfg.color}">${cfg.logo}</div><div class="store-info"><h3>${esc(p.name||p.title||'محصول')}</h3><p>${esc(cfg.name)}</p><p class="store-features">${p.price?`💰 ${new Intl.NumberFormat('fa-IR').format(p.price)} تومان`:'قیمت نامشخص'}</p></div>${url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer" class="store-button" style="background:${cfg.color}">مشاهده و خرید</a>`:'<span class="store-button" style="background:#999">لینک موجود نیست</span>'}</div>`;}
function handleSearchInput(query){clearTimeout(searchTimeout);if(query.trim().length<3)return;searchTimeout=setTimeout(()=>searchProducts(query.trim()),400);}
function handleSearchKey(event){if(event.key==='Enter'){event.preventDefault();performSmartSearch();}}
function performSmartSearch(){const input=document.getElementById('smartSearchInput');const query=input?.value.trim();if(!query)return alert('لطفاً نام محصول را وارد کنید');searchProducts(query);}
function quickSearch(term){const input=document.getElementById('smartSearchInput');if(input)input.value=term;performSmartSearch();}
