/* DigiYar V5 — Step 4 behavior: store-aware categories + compact expandable form */
(function(){'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const storeCategories={
  digikala:[['digital','کالای دیجیتال'],['home','خانه و آشپزخانه'],['fashion','مد و پوشاک'],['supermarket','کالاهای خوراکی و اساسی'],['beauty','زیبایی و سلامت'],['books','کتاب، لوازم تحریر و هنر'],['kids','اسباب‌بازی، کودک و نوزاد'],['sports','ورزش و سفر'],['tools-auto','ابزار، خودرو و موتورسیکلت'],['local','محصولات بومی و محلی'],['other','سایر']],
  snappshop:[['digital','کالای دیجیتال'],['beauty','زیبایی و سلامت'],['home','خانه و آشپزخانه'],['fashion','مد و پوشاک'],['culture','فرهنگ و هنر'],['mother-kid','مادر و کودک'],['sports','ورزش و سفر'],['auto-tools','ابزار و لوازم خودرو'],['supermarket','کالاهای روزمره و سوپرمارکتی'],['other','سایر']],
  torob:[['digital','موبایل و کالای دیجیتال'],['computer','لپ‌تاپ، کامپیوتر و اداری'],['supermarket','هایپرمارکت'],['home','لوازم خانگی'],['fashion','مد و پوشاک'],['beauty','زیبایی و بهداشت'],['av','صوتی و تصویری'],['auto','خودرو و سایر وسایل نقلیه'],['sports','ورزش و سرگرمی'],['other','سایر']],
  basalam:[['food','مواد غذایی'],['herbal','عطاری'],['beauty','آرایشی و بهداشتی'],['handmade','صنایع دستی'],['fashion','پوشاک'],['culture','محصولات فرهنگی'],['home','لوازم خانگی'],['sports','ورزش و سفر'],['local','محصولات محلی و سنتی'],['other','سایر']]
};
const categoryFields={
  mobile:[['usage','نوع استفاده',['عکاسی','بازی','کار روزمره','تولید محتوا']],['priorities','اولویت خرید',['دوربین','باتری','ارزش خرید','کیفیت']],['requirements','نیاز ضروری',['5G','حافظه بالا','شارژ سریع']],['constraints','محدودیت',['وزن کم','اندازه کوچک','قیمت پایین']]],
  digital:[['usage','نوع استفاده',['کار روزمره','سرگرمی','تولید محتوا','بازی']],['priorities','اولویت خرید',['کیفیت','قدرت','ارزش خرید','باتری']],['requirements','نیاز ضروری',['حافظه بالا','اتصال سریع','گارانتی']],['constraints','محدودیت',['وزن کم','اندازه کوچک','قیمت پایین']]],
  computer:[['usage','نوع استفاده',['کار اداری','برنامه‌نویسی','طراحی','بازی']],['priorities','اولویت خرید',['قدرت پردازش','باتری','نمایشگر','ارزش خرید']],['requirements','نیاز ضروری',['رم بالا','SSD','وزن کم']],['constraints','محدودیت',['وزن کم','اندازه کوچک','قیمت پایین']]],
  laptop:[['usage','نوع استفاده',['کار روزمره','برنامه‌نویسی','طراحی','بازی']],['priorities','اولویت خرید',['قدرت پردازش','باتری','صفحه‌نمایش','ارزش خرید']],['requirements','نیاز ضروری',['رم بالا','SSD','وزن کم']],['constraints','محدودیت',['وزن کم','اندازه کوچک','قیمت پایین']]],
  tablet:[['usage','نوع استفاده',['مطالعه','طراحی','سرگرمی','کار روزمره']],['priorities','اولویت خرید',['نمایشگر','باتری','وزن','ارزش خرید']],['requirements','نیاز ضروری',['حافظه بالا','قلم','سیم‌کارت']],['constraints','محدودیت',['وزن کم','اندازه کوچک','قیمت پایین']]],
  fashion:[['usage','نوع استفاده',['روزمره','رسمی','ورزشی','هدیه']],['priorities','اولویت خرید',['کیفیت','جنس','قیمت','برند']],['requirements','نیاز ضروری',['سایز دقیق','رنگ خاص','ارسال سریع']],['constraints','محدودیت',['قیمت پایین','سایز خاص']]],
  beauty:[['usage','نوع استفاده',['مصرف شخصی','مراقبت پوست','مراقبت مو','هدیه']],['priorities','اولویت خرید',['کیفیت','برند','ارزش خرید','ترکیبات']],['requirements','نیاز ضروری',['اصل بودن','تاریخ انقضا','گارانتی']],['constraints','محدودیت',['قیمت پایین','بدون عطر']]],
  home:[['usage','نوع استفاده',['مصرف روزمره','آشپزی','دکوراسیون','هدیه']],['priorities','اولویت خرید',['کیفیت','مصرف انرژی','ظرفیت','ارزش خرید']],['requirements','نیاز ضروری',['گارانتی','ارسال سریع','اندازه مناسب']],['constraints','محدودیت',['ابعاد کوچک','قیمت پایین']]],
  sports:[['usage','نوع استفاده',['ورزش خانگی','باشگاه','سفر و کمپ','تفریح']],['priorities','اولویت خرید',['کیفیت','وزن','دوام','ارزش خرید']],['requirements','نیاز ضروری',['اندازه مناسب','ضدآب','قابل حمل']],['constraints','محدودیت',['وزن کم','قیمت پایین']]],
  other:[['usage','نوع استفاده',['مصرف شخصی','کار روزمره','هدیه']],['priorities','اولویت خرید',['کیفیت','ارزش خرید','قیمت']],['requirements','نیاز ضروری',['گارانتی','ارسال سریع']],['constraints','محدودیت',['قیمت پایین','اندازه کوچک']]]
};
function setOptions(select,items,placeholder){if(!select)return;select.innerHTML='';const p=document.createElement('option');p.value='';p.textContent=placeholder;select.appendChild(p);items.forEach(([value,label])=>{const o=document.createElement('option');o.value=value;o.textContent=label;select.appendChild(o)});}
function renderFields(category){const box=$('v5DynamicFields');if(!box)return;const rows=categoryFields[category]||categoryFields.other;box.innerHTML=rows.map(([id,label,opts])=>`<label class="v5-field"><span>${esc(label)}</span><select id="${id}"><option value="">انتخاب کن</option>${opts.map(o=>`<option>${esc(o)}</option>`).join('')}</select></label>`).join('');}
function setupStructure(){const card=document.querySelector('.v5-profile-card'),grid=card?.querySelector('.form-grid'),storeField=$('storeSelect')?.closest('.v5-field'),category=$('v5Category'),budget=$('budgetMax'),dynamic=$('v5DynamicFields'),actions=card?.querySelector('.form-actions');if(!card||!grid||!storeField||!category||!dynamic)return;
 storeField.classList.add('v5-step4-store-field');const label=storeField.querySelector('span');if(label)label.textContent='انتخاب فروشگاه';const hint=$('v5StoreHint');if(hint)hint.textContent='با انتخاب فروشگاه، دسته‌بندی‌های همان فروشگاه نمایش داده می‌شود.';if(hint)hint.classList.add('v5-step4-store-hint');
 let upper=grid.querySelector('.v5-step4-upper');if(!upper){upper=document.createElement('div');upper.className='v5-step4-upper';grid.insertBefore(upper,storeField);upper.appendChild(storeField)}
 let panel=grid.querySelector('.v5-step4-panel');if(!panel){panel=document.createElement('div');panel.className='v5-step4-panel';panel.hidden=true;const moving=[category.closest('.v5-field'),budget?.closest('.v5-field'),dynamic,actions].filter(Boolean);moving.forEach(el=>panel.appendChild(el));grid.appendChild(panel)}
 let toggle=card.querySelector('.v5-step4-toggle');if(!toggle){toggle=document.createElement('button');toggle.type='button';toggle.className='v5-step4-toggle';toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-controls','v5Step4Panel');toggle.innerHTML='<span>جزئیات خرید</span><span class="v5-step4-toggle-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg></span>';panel.id='v5Step4Panel';card.insertBefore(toggle,card.querySelector('.v5-storage-note'))}
 const update=()=>{const open=toggle.getAttribute('aria-expanded')==='true';panel.hidden=!open;toggle.setAttribute('aria-expanded',String(open));};toggle.onclick=()=>{toggle.setAttribute('aria-expanded',String(toggle.getAttribute('aria-expanded')!=='true'));update()};update();
 const store=$('storeSelect');setOptions(store,[['digikala','دیجی‌کالا'],['snappshop','اسنپ‌شاپ'],['torob','ترب'],['basalam','باسلام']],'انتخاب فروشگاه');category.disabled=true;setOptions(category,[], 'ابتدا فروشگاه را انتخاب کنید');
 const refresh=()=>{const key=store.value;const list=storeCategories[key]||[];category.disabled=!key;setOptions(category,list,key?'انتخاب دسته‌بندی':'ابتدا فروشگاه را انتخاب کنید');if(hint)hint.textContent=key?'نتایج بر اساس فروشگاه انتخابی اولویت‌بندی می‌شوند.':'با انتخاب فروشگاه، دسته‌بندی‌های همان فروشگاه نمایش داده می‌شود.';if(!key){dynamic.innerHTML='';}else{category.value='';renderFields('other')}};
 store.addEventListener('change',refresh);category.addEventListener('change',()=>renderFields(category.value||'other'));refresh();
}
function init(){setupStructure()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();