const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET, OPTIONS","Access-Control-Allow-Headers":"Content-Type"};
const STORES={digikala:{id:"digikala",name:"دیجی‌کالا"},snappshop:{id:"snappshop",name:"اسنپ‌شاپ"}};
export default{async fetch(request){if(request.method==="OPTIONS")return new Response(null,{headers:CORS});const u=new URL(request.url),q=(u.searchParams.get("q")||"").trim();if(u.pathname==="/health")return json({status:"ok",version:"v5.1-product-resolver"},CORS);if(u.pathname!=="/api/search")return json({error:"Unknown endpoint"},CORS);if(!q)return json({success:false,error:"Missing q",results:[],total:0},CORS);const settled=await Promise.allSettled([searchDigikala(q),searchSnappShop(q)]);const results=[...(settled[0].status==="fulfilled"?settled[0].value:[]),...(settled[1].status==="fulfilled"?settled[1].value:[])].filter(isResolvedOffer).slice(0,10);return json({success:true,results,total:results.length,query:q,sources:{digikala:settled[0].status,snappshop:settled[1].status}},CORS)}};
function json(data,headers){return new Response(JSON.stringify(data),{headers:{...headers,"Content-Type":"application/json"}})}
async function fetchText(url){const r=await fetch(url,{headers:{Accept:"text/html,application/xhtml+xml,application/json","Accept-Language":"fa-IR,fa;q=0.9","User-Agent":"Mozilla/5.0 (compatible; DigiYar/5.1; +https://digiyar.ir)"},redirect:"follow"});if(!r.ok)throw Error("HTTP "+r.status);return r.text()}
async function fetchJson(url){const r=await fetch(url,{headers:{Accept:"application/json","Accept-Language":"fa-IR,fa;q=0.9","User-Agent":"Mozilla/5.0 (compatible; DigiYar/5.1)"},redirect:"follow"});if(!r.ok)throw Error("HTTP "+r.status);return r.json()}
async function searchDigikala(q){const urls=[`https://api.digikala.com/v1/search/?q=${encodeURIComponent(q)}&page=1`,`https://api.digikala.com/v2/search/?q=${encodeURIComponent(q)}&page=1`];for(const url of urls){try{const d=await fetchJson(url);const ps=d?.data?.products||d?.data?.data?.products;if(Array.isArray(ps)&&ps.length)return ps.slice(0,5).map(normalizeDigikala).filter(isResolvedOffer)}catch(e){}}return[]}
function normalizeDigikala(p){const id=p?.id||p?.product_id;const productUrl=id?`https://www.digikala.com/product/dkp-${id}/`:"";const price=p?.default_variant?.price?.selling_price??p?.price?.selling_price??p?.price??0;return{id:String(id||""),productId:String(id||""),name:p?.title_fa||p?.title_en||"بدون عنوان",productName:p?.title_fa||p?.title_en||"بدون عنوان",price:Number(price)||0,image:p?.images?.main?.url?.[0]||"",productUrl,url:productUrl,affiliateUrl:"",available:!!id,store:"digikala",storeName:STORES.digikala.name,source:"digikala-api",lastUpdated:new Date().toISOString()}}
async function searchSnappShop(q){const url=`https://snappshop.ir/search?q=${encodeURIComponent(q)}`;const html=await fetchText(url);const out=[];extractJsonLd(html,out);extractProductLinks(html,out);return dedupe(out).slice(0,5).map(normalizeSnapp).filter(isResolvedOffer)}
function extractJsonLd(html,out){const re=/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;let m;while((m=re.exec(html))){try{const d=JSON.parse(m[1]);walkJsonLd(d,out)}catch(e){}}}
function walkJsonLd(x,out){if(!x)return;if(Array.isArray(x)){x.forEach(v=>walkJsonLd(v,out));return}if(typeof x!=="object")return;const type=String(x["@type"]||"").toLowerCase();if(type.includes("product")){const offers=Array.isArray(x.offers)?x.offers[0]:x.offers||{};if(x.url)out.push({productId:x.sku||x.productID||x.mpn||"",productName:x.name||"",productUrl:x.url,price:offers.price||0,available:offers.availability?!/outofstock/i.test(String(offers.availability)):true,image:Array.isArray(x.image)?x.image[0]:x.image||"",source:"snappshop-jsonld"})}Object.values(x).forEach(v=>{if(v&&typeof v==="object")walkJsonLd(v,out)})}
function extractProductLinks(html,out){const re=/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))){const href=m[1];if(!/snappshop\.ir/i.test(href)||!/\/(?:product|p)\//i.test(href))continue;const text=m[2].replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();if(text)out.push({productId:extractId(href),productName:text,productUrl=new URL(href,"https://snappshop.ir").href,price:0,available:true,source:"snappshop-link"})}}
function extractId(url){const m=String(url).match(/(?:product|p)\/([^/?#]+)/i);return m?m[1]:""}
function dedupe(a){const seen=new Set();return a.filter(x=>{const k=x.productUrl||x.productId||x.productName;if(!k||seen.has(k))return false;seen.add(k);return true})}
function normalizeSnapp(x){return{...x,id:String(x.productId||extractId(x.productUrl)||""),productId:String(x.productId||extractId(x.productUrl)||""),name:x.productName||"بدون عنوان",productName:x.productName||"بدون عنوان",price:Number(x.price)||0,productUrl:x.productUrl||"",url:x.productUrl||"",image:x.image||"",available:x.available!==false,store:"snappshop",storeName:STORES.snappshop.name,source:x.source||"snappshop",lastUpdated:new Date().toISOString()}}
function isResolvedOffer(x){if(!x?.productId||!x?.productUrl)return false;try{const u=new URL(x.productUrl);return /^https?:$/.test(u.protocol)&&!/\/search(?:\/|\?|$)/i.test(u.pathname)}catch{return false}}
