const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET, OPTIONS","Access-Control-Allow-Headers":"Content-Type"};
const STORES={digikala:{id:"digikala",name:"دیجی‌کالا",affiliate:"https://aflo.ir/TrvNHEN8"},snappshop:{id:"snappshop",name:"اسنپ‌شاپ",affiliate:"https://aflo.ir/YPN05dL7"}};
export default{async fetch(request){if(request.method==="OPTIONS")return new Response(null,{headers:CORS});const u=new URL(request.url),q=(u.searchParams.get("q")||"").trim();if(u.pathname==="/health")return json({status:"ok",version:"v5.1-real-offer-search"},CORS);if(u.pathname!=="/api/search")return json({error:"Unknown endpoint"},CORS);if(!q)return json({success:false,error:"Missing q",results:[],total:0},CORS);const settled=await Promise.allSettled([searchDigikala(q),searchSnappShop(q)]);const dk=settled[0].status==="fulfilled"?settled[0].value:[];const ss=settled[1].status==="fulfilled"?settled[1].value:[];const results=[...dk,...ss].filter(isResolvedOffer).slice(0,10);return json({success:true,results,total:results.length,query:q,sources:{digikala:statusOf(settled[0],dk),snappshop:statusOf(settled[1],ss)}},CORS)}};
function statusOf(s,v){return s.status==="fulfilled"?(v.length?"fulfilled":"fulfilled_empty"):"rejected"}
function json(data,headers){return new Response(JSON.stringify(data),{headers:{...headers,"Content-Type":"application/json"}})}
async function request(url,accept){const r=await fetch(url,{headers:{Accept:accept,"Accept-Language":"fa-IR,fa;q=0.9,en;q=0.8","User-Agent":"Mozilla/5.0 (compatible; DigiYar/5.1; +https://digiyar-v5.petromosi.workers.dev)"},redirect:"follow"});if(!r.ok)throw Error("HTTP "+r.status);return r}
async function fetchJson(url){return(await request(url,"application/json")).json()}
async function fetchText(url){return(await request(url,"text/html,application/xhtml+xml,application/json")).text()}
async function searchDigikala(q){try{const d=await fetchJson(`https://api.digikala.com/v1/search/?q=${encodeURIComponent(q)}&page=1`);const ps=d?.data?.products||d?.data?.data?.products;if(Array.isArray(ps)&&ps.length)return ps.slice(0,5).map(normalizeDigikala).filter(isResolvedOffer)}catch(e){}try{const d=await fetchJson(`https://api.digikala.com/v2/search/?q=${encodeURIComponent(q)}&page=1`);const ps=d?.data?.products||d?.data?.data?.products;if(Array.isArray(ps)&&ps.length)return ps.slice(0,5).map(normalizeDigikala).filter(isResolvedOffer)}catch(e){}return searchDigikalaHtml(q)}
function normalizeDigikala(p){const id=p?.id||p?.product_id||p?.product?.id;const productUrl=id?`https://www.digikala.com/product/dkp-${id}/`:"";const price=p?.default_variant?.price?.selling_price??p?.default_variant?.price?.selling_price_fa??p?.price?.selling_price??p?.price??0;return{id:String(id||""),productId:String(id||""),name:p?.title_fa||p?.title_en||"بدون عنوان",productName:p?.title_fa||p?.title_en||"بدون عنوان",price:Number(String(price).replace(/,/g,""))||0,currency:"IRR",image:p?.images?.main?.url?.[0]||p?.images?.main?.url||"",productUrl,url:productUrl,affiliateUrl:affiliateUrl("digikala",productUrl),available:!!id,store:"digikala",storeName:STORES.digikala.name,source:"digikala-api",lastUpdated:new Date().toISOString()}}
async function searchDigikalaHtml(q){const html=await fetchText(`https://www.digikala.com/search/?q=${encodeURIComponent(q)}`);const out=[];extractProductLinks(html,/digikala\.com/i,/\/product\/dkp-/i,out,"digikala");return dedupe(out).slice(0,5).map(x=>({...x,affiliateUrl:affiliateUrl("digikala",x.productUrl)})).filter(isResolvedOffer)}
async function searchSnappShop(q){try{const html=await fetchText(`https://snappshop.ir/search?q=${encodeURIComponent(q)}`);const out=[];extractJsonLd(html,out);extractProductLinks(html,/snappshop\.ir/i,/\/(?:product|p)\//i,out,"snappshop");return dedupe(out).slice(0,5).map(normalizeSnapp).filter(isResolvedOffer)}catch(e){return[]}}
function extractJsonLd(html,out){const re=/<script[^>]+type=["']application\\/ld\\+json["'][^>]*>([\\s\\S]*?)<\\/script>/gi;let m;while((m=re.exec(html))){try{walkJsonLd(JSON.parse(m[1]),out)}catch(e){}}}
function walkJsonLd(x,out){if(!x)return;if(Array.isArray(x)){x.forEach(v=>walkJsonLd(v,out));return}if(typeof x!=="object")return;const type=String(x["@type"]||"").toLowerCase();if(type.includes("product")&&x.url){const offers=Array.isArray(x.offers)?x.offers[0]:x.offers||{};out.push({productId:x.sku||x.productID||x.mpn||extractId(x.url),productName:x.name||"",productUrl:x.url,price:offers.price||0,currency:offers.priceCurrency||"IRR",available:offers.availability?!/outofstock/i.test(String(offers.availability)):true,image:Array.isArray(x.image)?x.image[0]:x.image||"",source:"snappshop-jsonld"})}Object.values(x).forEach(v=>{if(v&&typeof v==="object")walkJsonLd(v,out)})}
function extractProductLinks(html,hostPattern,pathPattern,out,store){const re=/<a[^>]+href=["']([^"']+)["'][^>]*>([\\s\\S]*?)<\\/a>/gi;let m;while((m=re.exec(html))){const href=m[1];if(!hostPattern.test(href)||!pathPattern.test(href))continue;const text=m[2].replace(/<[^>]+>/g," ").replace(/\\s+/g," ").trim();const productUrl=new URL(href,store==="digikala"?"https://www.digikala.com":"https://snappshop.ir").href;if(!text)continue;out.push({productId:extractId(productUrl),productName:text,productUrl,price:0,available:true,source:store+"-html"})}}
function extractId(url){const m=String(url).match(/(?:dkp-|product\\/|p\\/)([A-Za-z0-9_-]+)/i);return m?m[1]:""}
function normalizeSnapp(x){const id=String(x.productId||extractId(x.productUrl)||"");return{...x,id,productId:id,name:x.productName||"بدون عنوان",productName:x.productName||"بدون عنوان",price:Number(String(x.price??0).replace(/,/g,""))||0,currency:x.currency||"IRR",productUrl:x.productUrl||"",url:x.productUrl||"",image:x.image||"",available:x.available!==false,store:"snappshop",storeName:STORES.snappshop.name,affiliateUrl:affiliateUrl("snappshop",x.productUrl||""),source:x.source||"snappshop",lastUpdated:new Date().toISOString()}}
function affiliateUrl(store,target){const base=STORES[store]?.affiliate;if(!base||!target)return"";return `${base}?p=${encodeURIComponent(target)}`}
function dedupe(a){const seen=new Set();return a.filter(x=>{const k=x.productUrl||x.productId||x.productName;if(!k||seen.has(k))return false;seen.add(k);return true})}
function isResolvedOffer(x){if(!x?.productId||!x?.productUrl)return false;try{const u=new URL(x.productUrl);return /^https?:$/.test(u.protocol)&&!/\/search(?:\/|\?|$)/i.test(u.pathname)&&!/\/(?:category|categories)(?:\/|\?|$)/i.test(u.pathname)}catch{return false}}
