const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET, OPTIONS","Access-Control-Allow-Headers":"Content-Type"};
const STORES={digikala:{id:"digikala",name:"دیجی‌کالا",affiliate:"https://aflo.ir/TrvNHEN8"},snappshop:{id:"snappshop",name:"اسنپ‌شاپ",affiliate:"https://aflo.ir/YPN05dL7"}};
function norm(s=""){return String(s).toLowerCase().replace(/[يى]/g,"ی").replace(/ك/g,"ک").replace(/[٬,]/g,"").replace(/\s+/g," ").trim()}
function money(n,u=""){const x=Number(n)||0;return !u||u==="تومان"?x:u==="هزار"?x*1e3:u==="میلیون"?x*1e6:u==="میلیارد"?x*1e9:x}
function parseQ(q=""){const n=norm(q),t=n.split(" ").filter(Boolean),brands=["سامسونگ","شیائومی","اپل","آیفون","هواوی","آنر","لنوو","ایسوس","اچ‌پی","hp","dell","acer"].filter(b=>t.includes(b));const range=n.match(/(\d+(?:\.\d+)?)\s*(?:تا|-|–)\s*(\d+(?:\.\d+)?)\s*(میلیون|میلیارد|هزار|تومان)?/i),max=n.match(/(?:زیر|کمتر از|حداکثر|تا)\s*(\d+(?:\.\d+)?)\s*(میلیون|میلیارد|هزار|تومان)?/i),min=n.match(/(?:بالای|بیشتر از|حداقل)\s*(\d+(?:\.\d+)?)\s*(میلیون|میلیارد|هزار|تومان)?/i);const price=range?{minPrice:money(range[1],range[3]),maxPrice:money(range[2],range[3])}:{minPrice:min?money(min[1],min[2]):null,maxPrice:max?money(max[1],max[2]):null};return{normalized:n,tokens:t,brands,price,keywords:t.filter(x=>!new Set(["برای","با","و","در","از","یک","این","آن","می","به","تومان","تومن","میلیون","میلیارد","هزار"]).has(x)&&!/^[0-9.]+$/.test(x))}}
function affiliate(store,url){const b=STORES[store]?.affiliate;return b&&url?`${b}?p=${encodeURIComponent(url)}`:""}
function valid(x){if(!x?.productId||!x?.productUrl)return false;try{const u=new URL(x.productUrl);return /^https?:$/.test(u.protocol)&&!/\/search(?:\/|\?|$)/i.test(u.pathname)}catch{return false}}
function rank(items,q){const z=parseQ(q);return items.filter(valid).filter(o=>(z.price.minPrice==null||o.price>=z.price.minPrice)&&(z.price.maxPrice==null||o.price<=z.price.maxPrice)).map(o=>{const n=norm(o.name||o.productName),score=(z.keywords||[]).reduce((s,w)=>s+(n.includes(norm(w))?10:0),0)+(z.brands.some(b=>n.includes(norm(b)))?30:0)+(o.availability==="in_stock"?8:0)+(o.price>0?3:0)+(o.affiliateUrl?2:0);return{...o,score}}).sort((a,b)=>b.score-a.score||(a.price||Infinity)-(b.price||Infinity))}
async function req(url,accept){const r=await fetch(url,{redirect:"follow",headers:{Accept:accept,"Accept-Language":"fa-IR,fa;q=0.9,en;q=0.8","User-Agent":"Mozilla/5.0 (compatible; DigiYar/5.1)"}});if(!r.ok)throw Error(`HTTP ${r.status}`);return r}
async function dk(q){for(const base of ["https://api.digikala.com/v1/search/","https://api.digikala.com/v2/search/"]){try{const r=await req(`${base}?q=${encodeURIComponent(q)}&page=1`,"application/json");const d=await r.json(),p=d?.data?.products||d?.data?.data?.products||[];if(p.length)return p.slice(0,10).map(x=>{const id=x?.id||x?.product_id||x?.product?.id,url=id?`https://www.digikala.com/product/dkp-${id}/`:"";const price=x?.default_variant?.price?.selling_price??x?.price?.selling_price??0;return{productId:String(id||""),id:String(id||""),name:x?.title_fa||x?.title_en||"",productName:x?.title_fa||x?.title_en||"",price:Number(String(price).replace(/,/g,""))||0,currency:"IRR",availability:id?"in_stock":"unknown",productUrl:url,url,affiliateUrl:affiliate("digikala",url),store:"digikala",storeId:"digikala",storeName:STORES.digikala.name,source:"digikala-api"}})}catch(e){}}return[]}
async function ss(q){try{const r=await req(`https://snappshop.ir/search?q=${encodeURIComponent(q)}`,"text/html,application/xhtml+xml,application/json"),h=await r.text(),out=[],re=/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;let m;while((m=re.exec(h))){try{walk(JSON.parse(m[1]),out)}catch(e){}}return out.map(x=>{const url=x.productUrl||x.url||"",id=String(x.productId||x.sku||x.productID||"");return{...x,id,productId:id,name:x.name||x.productName||"",productName:x.name||x.productName||"",price:Number(x.price||0),currency:x.currency||"IRR",availability:x.available===false?"out_of_stock":"in_stock",productUrl:url,url,affiliateUrl:affiliate("snappshop",url),store:"snappshop",storeId:"snappshop",storeName:STORES.snappshop.name,source:"snappshop-jsonld"}})}catch(e){return[]}}
function walk(x,out){if(!x)return;if(Array.isArray(x)){x.forEach(v=>walk(v,out));return}if(typeof x!=="object")return;const t=String(x["@type"]||"").toLowerCase();if(t.includes("product")&&(x.url||x.sku||x.productID)){const o=Array.isArray(x.offers)?x.offers[0]:x.offers||{};out.push({productId:x.sku||x.productID||x.mpn||"",name:x.name||"",productUrl:x.url||"",price:o.price||0,currency:o.priceCurrency||"IRR",available:o.availability?!/outofstock/i.test(o.availability):true})}Object.values(x).forEach(v=>v&&typeof v==="object"&&walk(v,out))}
export default{async fetch(request){if(request.method==="OPTIONS")return new Response(null,{headers:CORS});const u=new URL(request.url),q=(u.searchParams.get("q")||"").trim();if(u.pathname==="/health")return json({status:"ok",version:"v5.1-search-core"});if(u.pathname!=="/api/search")return json({error:"Unknown endpoint"});if(!q)return json({success:false,results:[],total:0,error:"Missing q"});const s=await Promise.allSettled([dk(q),ss(q)]),raw=s.flatMap(x=>x.status==="fulfilled"?x.value:[]),results=rank(raw,q).slice(0,10);return json({success:true,version:"v5.1",query:q,parsed:parseQ(q),results,total:results.length,sources:{digikala:s[0].status==="fulfilled"?(s[0].value.length?"fulfilled":"fulfilled_empty"):"rejected",snappshop:s[1].status==="fulfilled"?(s[1].value.length?"fulfilled":"fulfilled_empty"):"rejected"}})}};
function json(x){return new Response(JSON.stringify(x),{headers:{...CORS,"Content-Type":"application/json"}})}