name: Deploy DigiYar V5 Web App

on:
  push:
    branches: [v5]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-v5
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout V5
        uses: actions/checkout@v4

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload V5 site
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy V5
        id: deployment
        uses: actions/deploy-pages@v4
